import { Component } from '@angular/core';
import { Producto } from '../../../models/producto';
@Component({
  selector: 'app-torture-star',
  imports: [],
  templateUrl: './torture-star.html',
  styleUrl: './torture-star.css',
})
export class TortureStar {
  torture: Producto[] = [
      {
      id: 1,
      img: '',
      nombre: 'Bloodwash',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 2,
      img: '',
      nombre: 'Deadly Night',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 3,
      img: '',
      nombre: 'Ding Dong Dead',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 4,
      img: '',
      nombre: 'Evil in the House of Dr. Fleshenstein',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 5,
      img: '',
      nombre: 'Inferno City Massacre',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 6,
      img: '',
      nombre: 'Lakeview Cabin Collection',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 7,
      img: '',
      nombre: 'Night at the Gates of Hell',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 8,
      img: '',
      nombre: 'No One Lives Under the Lighthouse',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 9,
      img: '',
      nombre: 'Porksy\'s Revenge',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 10,
      img: '',
      nombre: 'Rewind Or Die',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 11,
      img: '',
      nombre: 'SEARCH PARTY',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 12,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/c/c3/G3YkxxRW4AEi0dO.png/revision/latest?cb=20251016174117',
      nombre: 'Skinfreak',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 7.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 13,
      img: '',
      nombre: 'Sniper Killer',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 14,
      img: '',
      nombre: 'The Booty Creek Cheek Freak',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 15,
      img: '',
      nombre: 'The Booty Creek Cheek Freak II: The De-Cheekening',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 16,
      img: '',
      nombre: 'These Trees Are Spectral Fingers',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 17,
      img: '',
      nombre: 'Tonight It Follows',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 18,
      img: '',
      nombre: 'The Horror Of Salazar House',
      desarrolladora: 'Torture Star Video',
      link: '/tortureStar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
  ];
}
