import { Component } from '@angular/core';
import { Producto } from '../../../models/producto';
@Component({
  selector: 'app-puppet-combo',
  imports: [],
  templateUrl: './puppet-combo.html',
  styleUrl: './puppet-combo.css',
})
export class PuppetCombo {
  puppet: Producto[] = [
  {
      id: 1,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/9/9a/A_ZqrRvCYAANbk2.jpg/revision/latest/scale-to-width-down/268?cb=20181127193158',
      nombre: 'Minotaur',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 2,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/1/12/Babysitter_bloodbath_vhs.png/revision/latest/scale-to-width-down/1000?cb=20210607100306',
      nombre: 'Babysitter Bloodbath',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 3,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/9/9a/Pdm_vhs.png/revision/latest/scale-to-width-down/268?cb=20211007184732',
      nombre: 'Power Drill Massacre',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 4,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/e/ef/Mcm_vhs.png/revision/latest/scale-to-width-down/268?cb=20211026142127',
      nombre: 'Meat Cleaver Mutilator',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 5,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/9/91/Texas_butcher_vhs.png/revision/latest?cb=20181212002535',
      nombre: 'Texas Butcher',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 6,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/4/4e/Pitchfork_massacre_official_cover.png/revision/latest?cb=20201205014733',
      nombre: 'Pitchfork Massacre',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 7,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/8/81/NR_vhs.jpg/revision/latest/scale-to-width-down/268?cb=20181203201448',
      nombre: 'Nightripper',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 8,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/e/e4/Buzzsaw_bldhaus.png/revision/latest?cb=20211122145214',
      nombre: 'Buzz-Saw Blood House',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 9,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/d/df/Pobts_vhs.png/revision/latest/scale-to-width-down/268?cb=20210722125421',
      nombre: 'Planet of Bloodthirsty Santa',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 10,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/b/b6/Night_shift_vhs_smll.png/revision/latest?cb=20221020210935',
      nombre: 'Night Shift',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 11,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/7/76/Spiders_vhs.png/revision/latest/scale-to-width-down/268?cb=20181024193708',
      nombre: 'Spiders',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 12,
      img: 'https://store-images.s-microsoft.com/image/apps.23865.13794259264775165.981f5991-3592-472c-af32-598bd0cf8390.57f0b1a1-61a8-4d04-9eb2-db1292bed1d0',
      nombre: 'Nun Massacre',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 13,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/0/0d/Feed_me_billy_cd_rom_cover_hd.png/revision/latest?cb=20220318215707',
      nombre: 'Feed Me Billy',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 14,
      img: '',
      nombre: 'Blood Maniac',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 15,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/b/bc/Tgs_vhs_smaller.png/revision/latest/scale-to-width-down/267?cb=20221028021902',
      nombre: 'The Glass Staircase',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 16,
      img: '',
      nombre: 'The Riverside Incident',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 17,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/c/ce/Day_7_cover.png/revision/latest/scale-to-width-down/268?cb=20191120143345',
      nombre: 'Day 7',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 18,
      img: '',
      nombre: 'Evil Clowns',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 19,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/1/12/Scary_tales_vol_1_vhs.png/revision/latest/scale-to-width-down/268?cb=20211012182219',
      nombre: 'Scary Tales Vol. 1',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 20,
      img: 'https://static.wikia.nocookie.net/puppetcombo/images/f/f6/YPZ6YJ.jpg/revision/latest/scale-to-width-down/268?cb=20201003011159',
      nombre: 'Samhain',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 21,
      img: '',
      nombre: 'Night Watch',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 22,
      img: '',
      nombre: 'Tenebra',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 23,
      img: 'https://m.media-amazon.com/images/M/MV5BNzJlZmJjNTMtYTkwZC00NGU0LWIzOWItYjAxNGMzM2Y2YWYxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
      nombre: 'Christmas Massacre',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 2.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 24,
      img: 'https://store-images.s-microsoft.com/image/apps.57418.14163413953167753.5fb76bc9-9bdf-4576-9079-0e674a1d536c.d5b61dc7-c7b4-4e39-8231-f6154f78d590',
      nombre: 'Murder House',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 25,
      img: 'https://image.api.playstation.com/vulcan/ap/rnd/202304/2618/42e39588e95f85e70c76a50a6830d2476e0f481136877cc2.png',
      nombre: 'Stay Out of the House',
      desarrolladora: 'Puppet Combo',
      link: '/puppetCombo',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
  ];
}
