import { Component } from '@angular/core';
import { Producto } from '../../../models/producto';

@Component({
  selector: 'app-chillas-art',
  imports: [],
  templateUrl: './chillas-art.html',
  styleUrl: './chillas-art.css',
})
export class ChillasArt {
  chilla: Producto[]=[
   {
      id: 1,
      img: '',
      nombre: 'UMIGARI',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 2,
      img: '',
      nombre: 'The Closing Shift',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 3,
      img: '',
      nombre: 'Parasocial',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 4,
      img: '',
      nombre: 'Shinkansen 0',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 5,
      img: '',
      nombre: 'The Bathhouse',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 6,
      img: '',
      nombre: 'The Convenience Store',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 7,
      img: '',
      nombre: 'Night Security',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 8,
      img: '',
      nombre: 'The Kidnap',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 9,
      img: '',
      nombre: 'The Karaoke',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 10,
      img: '',
      nombre: 'Aka Manto',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 11,
      img: '',
      nombre: 'Stigmatized Property',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 12,
      img: '',
      nombre: 'Missing Children',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 13,
      img: '',
      nombre: 'The Caregiver',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 14,
      img: '',
      nombre: 'Night Delivery',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 15,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big_2x/co7jeg.jpg',
      nombre: 'Jisatsu',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 2.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 16,
      img: '',
      nombre: 'The Radio Station',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 17,
      img: '',
      nombre: 'Inukai Tunnel',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 18,
      img: '',
      nombre: 'The Ghost Train',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 19,
      img: '',
      nombre: 'Yuki Onna',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 20,
      img: '',
      nombre: 'Hanako',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 21,
      img: '',
      nombre: 'Okaeri',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 22,
      img: '',
      nombre: 'Onryo',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 23,
      img: '',
      nombre: 'The Night Way Home',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 24,
      img: '',
      nombre: 'Teke Teke',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 25,
      img: '',
      nombre: 'Blame Him',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 26,
      img: '',
      nombre: 'Evie',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 27,
      img: '',
      nombre: 'Welcome Back Daddy',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 28,
      img: '',
      nombre: 'Sphaera',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 29,
      img: '',
      nombre: 'Jimmu',
      desarrolladora: 'Chilla\'s Art',
      link: '/chilla',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
  ]
}
