import { Component } from '@angular/core';
import { Producto } from '../../../models/producto';
import { CarritoCompras } from '../../../servicios/carrito';
@Component({
  selector: 'app-six-one-six-games',
  imports: [],
  templateUrl: './six-one-six-games.html',
  styleUrl: './six-one-six-games.css',
})
export class SixOneSixGames {
  six: Producto[] = [
    {
      id: 101,
      img: '/assets/killer.jpg',
      nombre: 'I am a Serial Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1,
      desc: 'Martin decidió unirse a una secta llamada "Los Iluminados", que busca dar vida a un ser misterioso para eliminar todo el mal del mundo. ¿Hasta dónde estás dispuesto a llegar para lograr tus metas?',
      cr1: 'https://img.itch.zone/aW1nLzEyNzcyODkyLnBuZw==/original/z2yhXR.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjE1NDAxNS8xMjc2Mzk1OC5wbmc=/347x500/%2BqoXM7.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjE1NDAxNS8xMjc2Mzk1My5wbmc=/347x500/saRoCe.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjE1NDAxNS8xMjc2Mzk1Mi5wbmc=/347x500/%2BoZjsk.png',
      disponibilidad: true,
    },
    {
      id: 102,
      img: '/assets/pop.png',
      nombre: 'Poop Killer 4',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1,
      desc: 'Tras la muerte del "Asesino de las Cacas", la gente está más tranquila y puede volver a defecar en paz. Pero un fanático decide imitar a este terrible asesino... Billy es dueño de una "Sex Shop", una tienda dirigida a hombres homosexuales. Después de que un cliente defeca y obstruye el baño, la situación se vuelve tensa.',
      cr1: 'https://img.itch.zone/aW1nLzEyMjcyOTgzLnBuZw==/original/tR0ZKb.png',
      cr2: 'https://img.itch.zone/aW1nLzk2OTQyNTUuZ2lm/original/ssSFnh.gif',
      cr3: 'https://img.itch.zone/aW1nLzk2OTQyOTUuZ2lm/original/R5y096.gif',
      cr4: 'https://img.itch.zone/aW1nLzk2OTQyODUuZ2lm/original/jydj9x.gif',
      disponibilidad: true,
    },
    {
      id: 103,
      img: '/assets/blood.jpg',
      nombre: 'Blood Camp',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Blood Camp es un juego de terror slasher de estilo retro, desarrollado por 616 Games y lanzado en 2022, que rinde homenaje a las películas de terror de bajo presupuesto de los años 80 y 90',
      cr1: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/header.jpg?t=1645726691',
      cr2: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/ss_4758dc5c34e9b0b88010c964f3ac9c697cda8cce.1920x1080.jpg?t=1645726691',
      cr3: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/ss_a2d7bd44771625b3c4c944ad1d5286fc907e38ce.1920x1080.jpg?t=1645726691',
      cr4: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/ss_e2445b0157bf84a5b076777e56b0bd014dd9639b.1920x1080.jpg?t=1645726691',
      disponibilidad: true,
    },
    {
      id: 104,
      img: '/assets/indicted.jpg',
      nombre: 'Indicted',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'INDICTED es un juego de terror psicológico en primera persona que explora los miedos de Arthur, un investigador policial con un pasado oscuro. Con gráficos y escenarios inmersivos, y un toque de terror de los años 80 y 90, ofrece una experiencia única de terror y supervivencia.',
      cr1: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/header.jpg?t=1635550118',
      cr2: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/ss_c5e348a8ed06d00417676aca7d8f0234c6449691.1920x1080.jpg?t=1635550118',
      cr3: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/ss_5fa528c412b2e791539b7aaa7bd5e74b80956bf9.1920x1080.jpg?t=1635550118',
      cr4: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/ss_0121a4fbb305d1ab5d6efb9344ba96e87de53f6e.1920x1080.jpg?t=1635550118',
      disponibilidad: true,
    },
    {
      id: 105,
      img: 'https://img.itch.zone/aW1nLzIwOTcwNzQwLnBuZw==/315x250%23c/5GgggS.png',
      nombre: 'Tales Beyond The Bomb: White Silence',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 106,
      img: 'https://img.itch.zone/aW1nLzIwMjM3NzU4LnBuZw==/315x250%23c/8KBtvH.png',
      nombre: 'Poop Killer: Flush or Die',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 107,
      img: 'https://img.itch.zone/aW1nLzE5NDk3MjI0LnBuZw==/315x250%23c/kT5z%2Fa.png',
      nombre: 'Tales Beyond The Bomb: The Last Vigil',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 108,
      img: 'https://img.itch.zone/aW1nLzE4NjYyODM3LnBuZw==/315x250%23c/zMdejl.png',
      nombre: 'Tales Beyond The Bomb: Pineville Night Stalker',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 109,
      img: 'https://img.itch.zone/aW1nLzE3NzQzMDM2LnBuZw==/315x250%23c/SgBU6A.png',
      nombre: '1873',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 110,
      img: 'https://img.itch.zone/aW1nLzE3MjcxNDAyLnBuZw==/315x250%23c/eA3mdn.png',
      nombre: 'Gears 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 111,
      img: 'https://img.itch.zone/aW1nLzE3MDk4MzY2LnBuZw==/315x250%23c/TS4O3q.png',
      nombre: 'Fart Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 112,
      img: 'https://img.itch.zone/aW1nLzE2ODk5MjQwLnBuZw==/315x250%23c/Rzfv4b.png',
      nombre: 'Halloween Revenge',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 113,
      img: 'https://img.itch.zone/aW1nLzE2NTU1NzkwLnBuZw==/315x250%23c/wpfVmU.png',
      nombre: 'Dad',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 114,
      img: 'https://img.itch.zone/aW1nLzE2MjczMjQzLnBuZw==/315x250%23c/YFNaZ7.png',
      nombre: 'We Are Not Alone: Contact',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 115,
      img: 'https://img.itch.zone/aW1nLzE1ODI1NDQyLnBuZw==/315x250%23c/rxtrR6.png',
      nombre: 'Trash Night',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 116,
      img: 'https://img.itch.zone/aW1nLzE1MjE4OTQ4LnBuZw==/315x250%23c/MduX65.png',
      nombre: 'Meat',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 117,
      img: 'https://img.itch.zone/aW1nLzE0OTI3NzI1LnBuZw==/315x250%23c/KyBbzj.png',
      nombre: 'Community',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 118,
      img: 'https://img.itch.zone/aW1nLzE0NDM2MTkxLnBuZw==/315x250%23c/lsd5pL.png',
      nombre: 'The Light Went Out',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 119,
      img: 'https://img.itch.zone/aW1nLzkwMjkzMjUucG5n/315x250%23c/hharzV.png',
      nombre: 'Poop Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 120,
      img: 'https://img.itch.zone/aW1nLzk2Mzc1MDMucG5n/315x250%23c/J%2BN%2F33.png',
      nombre: 'Poop Killer 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 121,
      img: 'https://img.itch.zone/aW1nLzk2Mzc1MTgucG5n/315x250%23c/uU4ZCH.png',
      nombre: 'Poop Killer 3',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 122,
      img: 'https://img.itch.zone/aW1nLzEwMzAzNTcyLnBuZw==/315x250%23c/OxONxG.png',
      nombre: 'Poop Killer 5',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 123,
      img: 'https://img.itch.zone/aW1nLzEwOTk1ODg0LnBuZw==/315x250%23c/pU6BDE.png',
      nombre: 'Poop Killer 6',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 124,
      img: 'https://img.itch.zone/aW1nLzEyMzQxOTQ3LnBuZw==/315x250%23c/rAOV%2Ft.png',
      nombre: 'Poop Killer 7',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 125,
      img: 'https://img.itch.zone/aW1nLzE0MzUxNzc2LnBuZw==/315x250%23c/51NtXP.png',
      nombre: 'Poop Killer 8',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 126,
      img: 'https://img.itch.zone/aW1nLzEzODgxMTQ4LnBuZw==/315x250%23c/T59R7A.png',
      nombre: 'Hello, I Came to Kill You',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 127,
      img: 'https://img.itch.zone/aW1nLzEzNjM4NDkwLnBuZw==/315x250%23c/pghT4n.png',
      nombre: 'Deer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 128,
      img: 'https://img.itch.zone/aW1nLzEyNTYzNDM5LmdpZg==/315x250%23c/v11sZx.gif',
      nombre: 'Hill Maniac',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 129,
      img: 'https://img.itch.zone/aW1nLzEyMDQzMjM2LnBuZw==/315x250%23c/2OVwSa.png',
      nombre: 'Bloody Woman',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 130,
      img: 'https://img.itch.zone/aW1nLzEwMzE1ODAxLnBuZw==/315x250%23c/vpif3k.png',
      nombre: 'Poop Killer Origins',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 131,
      img: 'https://img.itch.zone/aW1nLzkxNTA0OTYucG5n/315x250%23c/N1s4lJ.png',
      nombre: 'The Elevator',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 132,
      img: 'https://img.itch.zone/aW1nLzkxNDkzNzIuZ2lm/315x250%23c/4cAHCS.gif',
      nombre: 'Mold',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 133,
      img: 'https://img.itch.zone/aW1nLzExNDIyOTA5LnBuZw==/315x250%23c/Fh7Bfi.png',
      nombre: 'Mold 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 134,
      img: 'https://img.itch.zone/aW1nLzg3NzcyNTgucG5n/315x250%23c/RiyyYX.png',
      nombre: 'Truth Loop',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 135,
      img: 'https://img.itch.zone/aW1nLzEyODYxODExLnBuZw==/315x250%23c/QLcUCk.png',
      nombre: 'Truth Loop 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 136,
      img: 'https://img.itch.zone/aW1nLzk1OTM0NDQucG5n/315x250%23c/UJnE3o.png',
      nombre: 'After Midnight',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 137,
      img: 'https://img.itch.zone/aW1nLzEwNTQ3MjY0LnBuZw==/315x250%23c/M2Df0p.png',
      nombre: 'After Midnight 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 138,
      img: 'https://img.itch.zone/aW1nLzg4MzE2NzgucG5n/315x250%23c/5qxKMf.png',
      nombre: 'The House of Rats',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 139,
      img: 'https://img.itch.zone/aW1nLzExMzI1Mzg3LnBuZw==/315x250%23c/AEZ3rK.png',
      nombre: 'REC',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 140,
      img: 'https://img.itch.zone/aW1nLzExMjU4MTE1LnBuZw==/315x250%23c/QQv3zr.png',
      nombre: 'S.M.S',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 141,
      img: 'https://img.itch.zone/aW1nLzEwNDQ1MTg1LnBuZw==/315x250%23c/JV3GAx.png',
      nombre: 'Last Heir',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 142,
      img: 'https://img.itch.zone/aW1nLzkxNTA0MzUucG5n/315x250%23c/ikzKl0.png',
      nombre: 'Blood Burger',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 143,
      img: 'https://img.itch.zone/aW1nLzEyNzc2MTQwLnBuZw==/315x250%23c/e37ovm.png',
      nombre: 'Cycle',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 144,
      img: 'https://img.itch.zone/aW1nLzEwMDM2MTgwLnBuZw==/315x250%23c/AMM3Xl.png',
      nombre: 'Chicken Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 145,
      img: 'https://img.itch.zone/aW1nLzk5OTc5MDkucG5n/315x250%23c/RQh2ln.png',
      nombre: 'Xenomoon',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 146,
      img: 'https://img.itch.zone/aW1nLzEzMDI2NTAzLnBuZw==/315x250%23c/78izg9.png',
      nombre: 'Gears',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 147,
      img: 'https://img.itch.zone/aW1nLzk3NTM0MjMucG5n/315x250%23c/eb2f0J.png',
      nombre: 'R.I.P.',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 148,
      img: 'https://img.itch.zone/aW1nLzEyMzU5MDk1LnBuZw==/315x250%23c/wzoNmi.png',
      nombre: 'Night of Carnage',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 149,
      img: 'https://img.itch.zone/aW1nLzEwMjQ0NjE4LnBuZw==/315x250%23c/0n6amv.png',
      nombre: 'Endless Night',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 150,
      img: 'https://img.itch.zone/aW1nLzExODM2NzAzLnBuZw==/315x250%23c/cFvfh0.png',
      nombre: 'Endless Night 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 151,
      img: 'https://img.itch.zone/aW1nLzEwMTUwMzkyLnBuZw==/315x250%23c/cSqrKA.png',
      nombre: 'Dick Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 152,
      img: 'https://img.itch.zone/aW1nLzkzMDYxOTMucG5n/315x250%23c/YoRC%2Fd.png',
      nombre: 'We Are Not Alone',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 153,
      img: 'https://img.itch.zone/aW1nLzkyNTk4NTUucG5n/315x250%23c/yJ0gSK.png',
      nombre: 'Thursday The 12th',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 154,
      img: 'https://img.itch.zone/aW1nLzk2ODkwNTEucG5n/315x250%23c/WAp4jI.png',
      nombre: 'Legend Hunters',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 155,
      img: 'https://img.itch.zone/aW1nLzc5ODkxNDAucG5n/315x250%23c/PhUXFj.png',
      nombre: 'Midnight Tales Vol. 1',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 156,
      img: 'https://img.itch.zone/aW1nLzg0NDYxODcuZ2lm/315x250%23c/HC%2FH6v.gif',
      nombre: 'Midnight Tales Vol. 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 157,
      img: 'https://img.itch.zone/aW1nLzEwODQ4NDI0LnBuZw==/315x250%23c/LyaSMZ.png',
      nombre: 'Midnight Tales Vol. 3',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 158,
      img: 'https://img.itch.zone/aW1nLzkxNTAyMzkucG5n/315x250%23c/k95kWB.png',
      nombre: 'Night Revenge',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 159,
      img: 'https://img.itch.zone/aW1nLzkwNjA4MzMucG5n/315x250%23c/5HWmmU.png',
      nombre: 'Red Valley',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 160,
      img: 'https://img.itch.zone/aW1nLzExNjk4NjM0LnBuZw==/315x250%23c/Ucldjt.png',
      nombre: 'Evil Is Back',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 161,
      img: 'https://img.itch.zone/aW1nLzkxNTA3MDkucG5n/315x250%23c/VXjogr.png',
      nombre: 'The Clown’s Fun',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 162,
      img: 'https://img.itch.zone/aW1nLzg5NjQ4NDQuZ2lm/315x250%23c/ksH7cS.gif',
      nombre: 'The Island Mystery',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 163,
      img: 'https://img.itch.zone/aW1nLzk3MDMzMjYuanBn/315x250%23c/HH16dQ.jpg',
      nombre: 'Footage 1985',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 164,
      img: 'https://img.itch.zone/aW1nLzEyMzQ2OTk1LnBuZw==/315x250%23c/qhPg31.png',
      nombre: 'They Are Not Dead',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 165,
      img: 'https://img.itch.zone/aW1nLzkxNTkyNTMucG5n/315x250%23c/9dAnZL.png',
      nombre: 'Panic on Ice',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    }
  ];
 constructor(private carritoService: CarritoCompras) { }

  agregarAlCarrito(producto: Producto): void {
    this.carritoService.agregar(producto);
    alert(`${producto.nombre} agregado al carrito`);
  }
}
