import { Component } from '@angular/core';
import { Producto } from '../../../models/producto';
import { CarritoCompras } from '../../../servicios/carrito';
import { ListaDeseados } from '../../../servicios/favoritos';

@Component({
  selector: 'app-six-one-six-games',
  imports: [],
  templateUrl: './six-one-six-games.html',
  styleUrl: './six-one-six-games.css',
})
export class SixOneSixGames {
  six: Producto[] = [
    {
      id: 101,
      img: '/assets/killer.jpg',
      nombre: 'I am a Serial Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Martin decidió unirse a una secta llamada "Los Iluminados", que busca dar vida a un ser misterioso para eliminar todo el mal del mundo. ¿Hasta dónde estás dispuesto a llegar para lograr tus metas?',
      cr1: 'https://img.itch.zone/aW1nLzEyNzcyODkyLnBuZw==/original/z2yhXR.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjE1NDAxNS8xMjc2Mzk1OC5wbmc=/347x500/%2BqoXM7.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjE1NDAxNS8xMjc2Mzk1My5wbmc=/347x500/saRoCe.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjE1NDAxNS8xMjc2Mzk1Mi5wbmc=/347x500/%2BoZjsk.png',
      disponibilidad: true,
    },
    {
      id: 102,
      img: '/assets/pop.png',
      nombre: 'Poop Killer 4',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Tras la muerte del "Asesino de las Cacas", la gente está más tranquila y puede volver a defecar en paz. Pero un fanático decide imitar a este terrible asesino... Billy es dueño de una "Sex Shop", una tienda dirigida a hombres homosexuales. Después de que un cliente defeca y obstruye el baño, la situación se vuelve tensa.',
      cr1: 'https://img.itch.zone/aW1nLzEyMjcyOTgzLnBuZw==/original/tR0ZKb.png',
      cr2: 'https://img.itch.zone/aW1nLzk2OTQyNTUuZ2lm/original/ssSFnh.gif',
      cr3: 'https://img.itch.zone/aW1nLzk2OTQyOTUuZ2lm/original/R5y096.gif',
      cr4: 'https://img.itch.zone/aW1nLzk2OTQyODUuZ2lm/original/jydj9x.gif',
      disponibilidad: true,
    },
    {
      id: 103,
      img: '/assets/blood.jpg',
      nombre: 'Blood Camp',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Blood Camp es un juego de terror slasher de estilo retro, desarrollado por 616 Games y lanzado en 2022, que rinde homenaje a las películas de terror de bajo presupuesto de los años 80 y 90',
      cr1: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/header.jpg?t=1645726691',
      cr2: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/ss_4758dc5c34e9b0b88010c964f3ac9c697cda8cce.1920x1080.jpg?t=1645726691',
      cr3: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/ss_a2d7bd44771625b3c4c944ad1d5286fc907e38ce.1920x1080.jpg?t=1645726691',
      cr4: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/ss_e2445b0157bf84a5b076777e56b0bd014dd9639b.1920x1080.jpg?t=1645726691',
      disponibilidad: true,
    },
    {
      id: 104,
      img: '/assets/indicted.jpg',
      nombre: 'Indicted',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'INDICTED es un juego de terror psicológico en primera persona que explora los miedos de Arthur, un investigador policial con un pasado oscuro. Con gráficos y escenarios inmersivos, y un toque de terror de los años 80 y 90, ofrece una experiencia única de terror y supervivencia.',
      cr1: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/header.jpg?t=1635550118',
      cr2: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/ss_c5e348a8ed06d00417676aca7d8f0234c6449691.1920x1080.jpg?t=1635550118',
      cr3: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/ss_5fa528c412b2e791539b7aaa7bd5e74b80956bf9.1920x1080.jpg?t=1635550118',
      cr4: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/ss_0121a4fbb305d1ab5d6efb9344ba96e87de53f6e.1920x1080.jpg?t=1635550118',
      disponibilidad: true,
    },
    {
      id: 105,
      img: 'https://img.itch.zone/aW1nLzIwOTcwNzQwLnBuZw==/315x250%23c/5GgggS.png',
      nombre: 'Tales Beyond The Bomb: White Silence',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: 'Hace años, un grupo de jóvenes exploradores desapareció durante una expedición a una remota y gélida región montañosa. Semanas después, sus cuerpos fueron hallados dispersos por el terreno: descalzos, heridos y con expresiones de terror absoluto. El caso se cerró rápidamente. Sin respuestas. Sin supervivientes. Ahora, encarnas a un investigador decidido que regresa al lugar de los hechos en busca de la verdad. Acompañado únicamente por un guía local, debes seguir los pasos de la expedición fallida, enfrentándote al frío glacial, al creciente aislamiento y a la inquietante sensación de que algo —o alguien— aún permanece en esas montañas. Cada paso te acerca a la verdad. Pero algunas verdades nunca deberían ser descubiertas.',
      cr1: 'https://img.itch.zone/aW1nLzIwOTcwNjQyLnBuZw==/original/Na1fqz.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMzUxOTY4Ni8yMDk3MDc0Ni5wbmc=/347x500/H9FMVl.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMzUxOTY4Ni8yMDk3MDc0OS5wbmc=/347x500/g%2F89k7.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMzUxOTY4Ni8yMDk3MDc0OC5wbmc=/347x500/vXQ2fh.png',
      disponibilidad: false,
    },
    {
      id: 106,
      img: 'https://img.itch.zone/aW1nLzIwMjM3NzU4LnBuZw==/315x250%23c/8KBtvH.png',
      nombre: 'Poop Killer: Flush or Die',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 4.99,
      desc:'Bob y Case solo querían pasar una noche tranquila en casa... pero el destino (y un inodoro atascado) tenían otros planes. En los suburbios de Nueva York en 1985, dos traficantes de marihuana pasan la noche comiendo, fumando y saldando cuentas. Pero cuando un amigo despistado ignora una advertencia importante y decide defecar en un inodoro roto, comienza la pesadilla. El Asesino de las Cacas ha escapado del manicomio. Está ahí fuera. Y no perdona. Ahora, Bob y Case deben sobrevivir a una noche de locura absoluta, donde un paso en falso podría ser el último. ¡Tira de la cadena... o muere!',
      cr1: 'https://img.itch.zone/aW1nLzIwMjM3NTgxLnBuZw==/original/oVZMZo.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMzM5MDEwMy8yMDIzNzcyMy5wbmc=/347x500/nd5fg5.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMzM5MDEwMy8yMDIzNzcyMi5wbmc=/347x500/11%2Fpqs.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMzM5MDEwMy8yMDIzNzcxOS5wbmc=/347x500/6s3eOL.png',
      disponibilidad: true,
    },
    {
      id: 107,
      img: 'https://img.itch.zone/aW1nLzE5NDk3MjI0LnBuZw==/315x250%23c/kT5z%2Fa.png',
      nombre: 'Tales Beyond The Bomb: The Last Vigil',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 4.99,
      desc: 'Nick Harrison, el nuevo guardia de seguridad del cementerio de Guadalupe, cree que tendrá un turno de noche tranquilo. Pero al caer la noche, pronto se da cuenta de su terrible error. El cementerio alberga algo más que los muertos.',
      cr1: 'https://img.itch.zone/aW1nLzE5NDk3MTMyLnBuZw==/original/OIDLOV.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMzI2NjAzMS8xOTQ5NzE4MC5wbmc=/347x500/qmEhMn.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMzI2NjAzMS8xOTQ5NzE3MC5wbmc=/347x500/VIi8pK.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMzI2NjAzMS8xOTQ5NzE3NC5wbmc=/347x500/cjqCkE.png',
      disponibilidad: true,
    },
    {
      id: 108,
      img: 'https://img.itch.zone/aW1nLzE4NjYyODM3LnBuZw==/315x250%23c/zMdejl.png',
      nombre: 'Tales Beyond The Bomb: Pineville Night Stalker',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Tras la inesperada muerte de su madre, Megan recibe una llamada sobre una herencia repentina y misteriosa que la espera en el desolado pueblo de Pineville. Junto a su compañero de trabajo, Lenny, se embarca en una aventura que debería ser sencilla, pero que pronto se convierte en una red de peligros y engaños.',
      cr1: 'https://img.itch.zone/aW1nLzE4NDg3Mjg3LnBuZw==/original/3Pn%2BGB.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMzA5MTYxMS8xODQ4NzI5MS5wbmc=/347x500/nCTC6E.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMzA5MTYxMS8xODQ4NzI5Mi5wbmc=/347x500/cp6XzZ.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMzA5MTYxMS8xODQ4NzI5NC5wbmc=/347x500/%2FPLEgK.png',
      disponibilidad: true,
    },
    {
      id: 109,
      img: 'https://img.itch.zone/aW1nLzE3NzQzMDM2LnBuZw==/315x250%23c/SgBU6A.png',
      nombre: '1873',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Irving es un sheriff famoso por cazar brujas y llevarlas a la horca. Recibe una llamada de auxilio de un pequeño pueblo atormentado por una bruja... Al llegar al pueblo, se da cuenta de que Dios ha abandonado ese lugar.',
      cr1: 'https://img.itch.zone/aW1nLzE3NzQzMTA3LnBuZw==/original/MwdfYK.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjk1NTYxNC8xNzc2NzkyNy5wbmc=/347x500/BopuHP.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjk1NTYxNC8xNzc2NzkzMi5wbmc=/347x500/S9YdkB.png',
      cr4: 'https://img.itch.zone/aW1nLzE3NzY3OTA2LmdpZg==/original/%2FXO8HS.gif',
      disponibilidad: true,
    },
    {
      id: 110,
      img: 'https://img.itch.zone/aW1nLzE3MjcxNDAyLnBuZw==/315x250%23c/eA3mdn.png',
      nombre: 'Gears 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Tras la muerte de su hijo, Josh ve cómo su vida se destruye lentamente... El asesino de su hijo anda suelto y hay varias personas a las que culpar por esta impunidad.',
      cr1: 'https://img.itch.zone/aW1nLzE3MjcxMDkxLnBuZw==/original/KDkVYP.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjg4ODA1OC8xNzI3MjE2NC5wbmc=/347x500/0PM8w2.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjg4ODA1OC8xNzI3MjE1Ni5wbmc=/347x500/6Q%2BDN0.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjg4ODA1OC8xNzI3MjE2Mi5wbmc=/347x500/mD2O1E.png',
      disponibilidad: true,
    },
    {
      id: 111,
      img: 'https://img.itch.zone/aW1nLzE3MDk4MzY2LnBuZw==/315x250%23c/TS4O3q.png',
      nombre: 'Fart Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Casey va a trabajar de noche a un puesto de hamburguesas para ayudar a su amigo Jeff. Pero un mendigo enfadado le arruinará la noche...',
      cr1: 'https://img.itch.zone/aW1nLzE3MDk4MzM5LnBuZw==/original/PP2ne%2F.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjg2MDUzOC8xNzA5ODczNS5wbmc=/347x500/GZIC2k.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjg2MDUzOC8xNzA5ODczNi5wbmc=/347x500/eIa0j7.png',
      cr4: 'https://img.itch.zone/aW1nLzE3MDk4NTIyLmdpZg==/original/hhSf0O.gif',
      disponibilidad: true,
    },
    {
      id: 112,
      img: 'https://img.itch.zone/aW1nLzE2ODk5MjQwLnBuZw==/315x250%23c/Rzfv4b.png',
      nombre: 'Halloween Revenge',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'El primer trabajo de Freddy en un minimercado comienza la noche de Halloween; va a trabajar de noche. Pero se topa con un cruel asesino que busca venganza... ¿El motivo de la venganza?... Él no lo sabe.',
      cr1: 'https://img.itch.zone/aW1nLzE2ODgwNTU0LnBuZw==/original/U3ZH2k.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjgyNTQ5MS8xNjg5ODk2My5wbmc=/347x500/MgiuaL.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjgyNTQ5MS8xNjg5ODk1OC5wbmc=/347x500/s30%2BM9.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjgyNTQ5MS8xNjg5ODk1Ny5wbmc=/347x500/3WlVh9.png',
      disponibilidad: true,
    },
    {
      id: 113,
      img: 'https://img.itch.zone/aW1nLzE2NTU1NzkwLnBuZw==/315x250%23c/wpfVmU.png',
      nombre: 'Dad',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Harry recibe un mensaje del padre que nunca conoció. Su padre quiere verlo y enmendar el error que cometió al abandonarlo cuando era niño. Tras el encuentro entre padre e hijo... Harry empieza a sospechar que su padre oculta algo.',
      cr1: 'https://img.itch.zone/aW1nLzE2NTU1NTk3LnBuZw==/original/rqgBid.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjc3NDY4Mi8xNjU1NzE1MS5wbmc=/347x500/CP%2FraK.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjc3NDY4Mi8xNjU1NzE0OS5wbmc=/347x500/jppUJv.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjc3NDY4Mi8xNjU1NzE1Ny5wbmc=/347x500/WJt9yn.png',
      disponibilidad: true,
    },
    {
      id: 114,
      img: 'https://img.itch.zone/aW1nLzE2MjczMjQzLnBuZw==/315x250%23c/YFNaZ7.png',
      nombre: 'We Are Not Alone: Contact',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Tras la muerte de su esposa, Monty decide mudarse a una zona apartada de la ciudad para llevar una vida más tranquila con su perro Mike. Tras vivir allí un tiempo, comienza a notar la presencia de luces extrañas en el cielo nocturno... Como si algo lo estuviera observando.',
      cr1: 'https://img.itch.zone/aW1nLzE2MjgzNzI1LnBuZw==/original/503U8Q.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjcyODQwMC8xNjI3NDM5Ny5wbmc=/347x500/jOWZBD.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjcyODQwMC8xNjI3NDM5NS5wbmc=/347x500/XncGHn.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjcyODQwMC8xNjI3NDM5MC5wbmc=/347x500/e48KNM.png',
      disponibilidad: true,
    },
    {
      id: 115,
      img: 'https://img.itch.zone/aW1nLzE1ODI1NDQyLnBuZw==/315x250%23c/rxtrR6.png',
      nombre: 'Trash Night',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Joseph trabaja en el turno de noche como basurero... Pero su verdadera pasión es la fotografía. Tras ser contratado para tomar algunas fotos de la casa abandonada de un famoso asesino en serie... las cosas empiezan a ponerse siniestras.',
      cr1: 'https://img.itch.zone/aW1nLzE1ODI1MzE1LnBuZw==/original/hIX%2F6g.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjY1NjA0MC8xNTgyNTY4NS5wbmc=/347x500/p2RNnB.png',
      cr3: 'https://img.itch.zone/aW1nLzE1ODI1MzY3LmdpZg==/original/d2TSUr.gif',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjY1NjA0MC8xNTgyNTY4OC5wbmc=/347x500/YvyQ3S.png',
      disponibilidad: true,
    },
    {
      id: 116,
      img: 'https://img.itch.zone/aW1nLzE1MjE4OTQ4LnBuZw==/315x250%23c/MduX65.png',
      nombre: 'Meat',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Tras la muerte de su padre, Jerry y su hermano Cris se hacen cargo del restaurante que era la gran pasión de su padre. Para evitar que el restaurante quiebre, deciden hacer cosas terribles.',
      cr1: 'https://img.itch.zone/aW1nLzE1MjA1NTg3LnBuZw==/original/Qh7KLs.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjU1NDMyNy8xNTE5OTczMS5wbmc=/347x500/f2bOd7.png',
      cr3: 'https://img.itch.zone/aW1nLzE1MjE4NTg5LmdpZg==/original/SnhtWC.gif',
      cr4: 'https://img.itch.zone/aW1nLzE1MjE4NTUyLmdpZg==/original/dIKCN8.gif',
      disponibilidad: true,
    },
    {
      id: 117,
      img: 'https://img.itch.zone/aW1nLzE0OTI3NzI1LnBuZw==/315x250%23c/KyBbzj.png',
      nombre: 'Community',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Marky es un joven que huye de la policía y decide mudarse a un lugar aislado con pocos vecinos. Tras mudarse a una pequeña comunidad, descubre que sus nuevos vecinos no son muy normales.',
      cr1: 'https://img.itch.zone/aW1nLzE0OTI3NDk0LnBuZw==/original/a5tBXY.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjUxMDY2NS8xNDkyNzQ4MC5wbmc=/347x500/vFHwLj.png',
      cr3: 'https://img.itch.zone/aW1nLzE0OTI3NjAzLmdpZg==/original/tXMdFe.gif',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjUxMDY2NS8xNDkyNzQ3OC5wbmc=/347x500/Pt2OOT.png',
      disponibilidad: true,
    },
    {
      id: 118,
      img: 'https://img.itch.zone/aW1nLzE0NDM2MTkxLnBuZw==/315x250%23c/lsd5pL.png',
      nombre: 'The Lights Went Out',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Tu coche se avería en una carretera desierta y oscura, buscas ayuda... quizás tu única opción sea llamar a la puerta de una casa siniestra, aislada de todo.',
      cr1: 'https://img.itch.zone/aW1nLzE0NDM2MTEzLnBuZw==/original/IeCddw.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjQzNzc0Ny8xNDQzNjI0Ny5wbmc=/347x500/6Nf2Xi.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjQzNzc0Ny8xNDQzNjI0OC5wbmc=/347x500/7S%2FNy6.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjQzNzc0Ny8xNDQzNjI1MC5wbmc=/347x500/STbJ9W.png',
      disponibilidad: true,
    },
    {
      id: 119,
      img: 'https://img.itch.zone/aW1nLzkwMjkzMjUucG5n/315x250%23c/hharzV.png',
      nombre: 'Poop Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Un asesino que mata a la gente que defeca y no tira de la cadena... Jhon trabaja en el turno de noche en una tienda de cintas VHS. Después de que un cliente obstruya el inodoro con excremento... el asesino de excrementos perseguirá a John.',
      cr1: 'https://i.ytimg.com/vi/yBwLV3MwXh0/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTU0NzA1Mi85MDI5MTkwLmpwZw==/347x500/EdfBmC.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTU0NzA1Mi85MDI5MTk2LmpwZw==/347x500/tEmauV.jpg',
      cr4: 'https://img.itch.zone/aW1nLzkwMjk2NzYuZ2lm/original/Q%2FF%2BjB.gif',
      disponibilidad: true,
    },
    {
      id: 120,
      img: 'https://img.itch.zone/aW1nLzk2Mzc1MDMucG5n/315x250%23c/J%2BN%2F33.png',
      nombre: 'Poop Killer 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Billy es un traficante de marihuana y vive con su amigo Jamal en un apartamento. Venden y fuman mucha hierba... Después de que tu amigo defeca en tu inodoro... el asesino de la caca viene a visitarte.',
      cr1: 'https://img.itch.zone/aW1nLzkxNjUxMzIucG5n/original/7L0st7.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTU2OTU1My85MTY1MDA4LmpwZw==/347x500/tkcCo%2B.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTU2OTU1My85MTY1MDAyLmpwZw==/347x500/jBbWCY.jpg',
      cr4: 'https://img.itch.zone/aW1nLzkxNjUxMDcuZ2lm/original/5LjSpa.gif',
      disponibilidad: true,
    },
    {
      id: 121,
      img: 'https://img.itch.zone/aW1nLzk2Mzc1MTgucG5n/315x250%23c/uU4ZCH.png',
      nombre: 'Poop Killer 3',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Robert es dueño de un club nocturno, el año es 1985. Después de que un cliente defeca y no tira de la cadena... el Asesino de Cacas aparecerá para traerte un gran trozo de mierda.',
      cr1: 'https://img.itch.zone/aW1nLzkxOTk3NDAucG5n/original/pXSZG%2F.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTU3NTE5OS85MjAwMjE0LmpwZw==/347x500/QbY2f5.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTU3NTE5OS85MjAwMjMzLmpwZw==/347x500/mcndDk.jpg',
      cr4: 'https://img.itch.zone/aW1nLzkyMDAzNjYuZ2lm/original/W8c19q.gif',
      disponibilidad: true,
    },
    {
      id: 122,
      img: 'https://img.itch.zone/aW1nLzEwMzAzNTcyLnBuZw==/315x250%23c/OxONxG.png',
      nombre: 'Poop Killer 5',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Mike y sus amigos, Mia, Samantha y Josh, alquilan una cabaña para pasar las vacaciones de verano de la universidad. Su plan era divertirse y aislarse de la ciudad... Pero un pequeño percance en el inodoro les convertirá la vida en un infierno...',
      cr1: 'https://i.ytimg.com/vi/8xxAz-7tMcM/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTc1MTM1MC8xMDMwMzAyMi5qcGc=/347x500/es%2BE8%2F.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTc1MTM1MC8xMDMwMzAzOC5qcGc=/347x500/3Nm7XE.jpg',
      cr4: 'https://img.itch.zone/aW1nLzEwMzAzMjY4LmdpZg==/original/Ie4a9r.gif',
      disponibilidad: true,
    },
    {
      id: 123,
      img: 'https://img.itch.zone/aW1nLzEwOTk1ODg0LnBuZw==/315x250%23c/pU6BDE.png',
      nombre: 'Poop Killer 6',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Billy tiene un coffeeshop en Ámsterdam y sirve buena marihuana a sus clientes. Después de que el inodoro se atasque con mucha mierda... el Asesino de Caca hará que tu vida y la de tus amigos sean un infierno.',
      cr1: 'https://i.ytimg.com/vi/BtxwmAk2eYM/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTg3MTc4Ni8xMDk5NTkyMC5qcGc=/347x500/qYBWRa.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTg3MTc4Ni8xMDk5NTkxNS5qcGc=/347x500/vW70HR.jpg',
      cr4: 'https://img.itch.zone/aW1nLzEwOTk1ODI4LmdpZg==/original/aMiCi0.gif',
      disponibilidad: true,
    },
    {
      id: 124,
      img: 'https://img.itch.zone/aW1nLzEyMzQxOTQ3LnBuZw==/315x250%23c/rAOV%2Ft.png',
      nombre: 'Poop Killer 7',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'El dueño de una tienda de artículos de baño tendrá que desafiar al asesino de excremento para sobrevivir. Enfrentándose a retos mortales para recuperar las infinitas joyas de mierda.',
      cr1: 'https://img.itch.zone/aW1nLzEyMzQxODE2LnBuZw==/original/xmUBK7.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjA5NzUzNS8xMjM0MjAwNy5wbmc=/347x500/E5jwX0.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjA5NzUzNS8xMjM0MjAwNi5wbmc=/347x500/VtIli6.png',
      cr4: 'https://img.itch.zone/aW1nLzEyMzQxODU5LmdpZg==/original/peRYlF.gif',
      disponibilidad: true,
    },
    {
      id: 125,
      img: 'https://img.itch.zone/aW1nLzE0MzUxNzc2LnBuZw==/315x250%23c/51NtXP.png',
      nombre: 'Poop Killer 8',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Pocos años después del ataque del Asesino de las Cacas a una tienda de alquiler de cintas VHS, defecar está oficialmente prohibido. Alex está en su primer turno de noche en la tienda de VHS; aceptó trabajar durante la Navidad porque necesitaba algo de dinero extra. Tras una inevitable confusión, el temido asesino de excrementos se pone un traje de Papá Noel para su ataque de mierda.',
      cr1: 'https://img.itch.zone/aW1nLzE0MzUxNTM5LnBuZw==/original/lA9q5k.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTYwOTU1OC85NDIwNDY4LmpwZw==/347x500/pkns%2FH.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTYwOTU1OC85NDIwNDcwLmpwZw==/347x500/sEU98u.jpg',
      cr4: 'https://img.itch.zone/aW1hZ2UvMTYwOTU1OC85NDIwNDcxLmpwZw==/347x500/QllKcP.jpg',
      disponibilidad: true,
    },
    {
      id: 126,
      img: 'https://img.itch.zone/aW1nLzEzODgxMTQ4LnBuZw==/315x250%23c/T59R7A.png',
      nombre: 'Hello, I Came to Kill You',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Lincoln es un chico soltero que decide aventurarse en internet para buscar novia. Sí, encuentra una novia preciosa... loca y psicótica.',
      cr1: 'https://img.itch.zone/aW1nLzEzODgxMDM5LnBuZw==/original/4lMPoO.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjM0Mjk3MS8xMzg4MTAzMC5wbmc=/347x500/5ooRUa.png',
      cr3: 'https://img.itch.zone/aW1nLzEzODgxMjEyLmdpZg==/original/VFy%2BXu.gif',
      cr4: 'https://img.itch.zone/aW1nLzEzODgxMjIzLmdpZg==/original/tja%2Flv.gif',
      disponibilidad: true,
    },
    {
      id: 127,
      img: 'https://img.itch.zone/aW1nLzEzNjM4NDkwLnBuZw==/315x250%23c/pghT4n.png',
      nombre: 'Deer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Samuell vive aislado en su casa a orillas de un lago; su gran pasión es la caza de ciervos. Pero pronto se dará cuenta de que cosechará todo lo que ha sembrado.',
      cr1: 'https://img.itch.zone/aW1nLzEzNjM4NDA4LnBuZw==/original/ELQvVV.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjI5ODE4MC8xMzY0NDgxOC5wbmc=/347x500/oOWwdG.png',
      cr3: 'https://img.itch.zone/aW1nLzEzNjQ0NzY2LmdpZg==/original/B7%2Fdna.gif',
      cr4: 'https://img.itch.zone/aW1nLzEzNjQ0NzYwLmdpZg==/original/nyufwN.gif',
      disponibilidad: true,
    },
    {
      id: 128,
      img: 'https://img.itch.zone/aW1nLzEyNTYzNDM5LmdpZg==/315x250%23c/v11sZx.gif',
      nombre: 'Hill Maniac',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'El reportero Martin Rilley quiere impulsar su carrera y necesita una buena historia. Decide ir a la cabaña de uno de los asesinos en serie más grandes de los años 80, que se encuentra en la cima de una colina. El asesino, conocido como el "Maníaco de la Colina", secuestraba niños, los torturaba y los asesinaba. La policía nunca lo encontró y sigue prófugo hasta el día de hoy. Las imágenes del lugar serían algo inaudito...',
      cr1: 'https://img.itch.zone/aW1nLzEyNTYyOTMzLnBuZw==/original/BOLQEf.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjEzMTkyOS8xMjU2MzMyMy5wbmc=/347x500/aJTPcb.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjEzMTkyOS8xMjU2MzMyNi5wbmc=/347x500/%2BF7Zj0.png',
      cr4: 'https://img.itch.zone/aW1nLzEyNTYzNTI1LmdpZg==/original/AqwdTB.gif',
      disponibilidad: true,
    },
    {
      id: 129,
      img: 'https://img.itch.zone/aW1nLzEyMDQzMjM2LnBuZw==/315x250%23c/2OVwSa.png',
      nombre: 'Bloody Woman',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Un joven acepta un trabajo en una lavandería en horario nocturno. Pero descubre que algo terrible ha ocurrido allí y su vida corre peligro.',
      cr1: 'https://img.itch.zone/aW1nLzEyMDQzMTI5LnBuZw==/original/SD%2Bn57.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjA0NzU2NS8xMjA0MzI5NC5wbmc=/347x500/dEnpqn.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjA0NzU2NS8xMjA0MzI5NS5wbmc=/347x500/bLr%2F9S.png',
      cr4: 'https://img.itch.zone/aW1nLzEyMDQzNjgyLmdpZg==/original/6nur0D.gif',
      disponibilidad: true,
    },
    {
      id: 130,
      img: 'https://img.itch.zone/aW1nLzEwMzE1ODAxLnBuZw==/315x250%23c/vpif3k.png',
      nombre: 'Poop Killer Origins',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Harry es dueño de una pequeña hamburguesería y trabaja solo. Tras enfurecer a un cliente, tendrá que hacer lo que sea para sobrevivir a este tipo tan loco.',
      cr1: 'https://i.ytimg.com/vi/QCZa1ROyBQ0/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTYwOTU1OC85NDIwNDY1LmpwZw==/347x500/68STQX.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTYwOTU1OC85NDIwNDc1LmpwZw==/347x500/Mi%2B4FX.jpg',
      cr4: 'https://img.itch.zone/aW1nLzk0MjA0OTMuZ2lm/original/RGsWff.gif',
      disponibilidad: true,
    },
    {
      id: 131,
      img: 'https://img.itch.zone/aW1nLzkxNTA0OTYucG5n/315x250%23c/N1s4lJ.png',
      nombre: 'The Elevator',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Josh lleva una semana trabajando en la recepción de un hotel en el turno de noche. Tras darse cuenta de que en el ascensor del lugar hay un misterio... comienza a investigar para averiguar qué está sucediendo.',
      cr1: 'https://img.itch.zone/aW1nLzg4NDkwMTIucG5n/original/j3gAkI.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTUxNzQxNC84ODQ5NDIyLmpwZw==/347x500/3QyBZ%2B.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTUxNzQxNC84ODQ5NDE4LmpwZw==/347x500/RmBMbb.jpg',
      cr4: 'https://img.itch.zone/aW1nLzg4NDk2MjguZ2lm/original/Zs6tQ%2B.gif',
      disponibilidad: true,
    },
    {
      id: 132,
      img: 'https://img.itch.zone/aW1nLzkxNDkzNzIuZ2lm/315x250%23c/4cAHCS.gif',
      nombre: 'Mold',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Jack y Sara viven en una granja aislada de todo. Cuando alguien deja una caja misteriosa en la puerta de su casa, las cosas empiezan a ponerse raras. Dentro de la caja hay un antiguo amuleto de origen desconocido. El amuleto tiene una terrible maldición... la maldición del moho.',
      cr1: 'https://img.itch.zone/aW1nLzkxNDgzMTQucG5n/original/hGdTtx.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTU2NjkzNy85MTQ5MzM4LmpwZw==/347x500/ito0PC.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTU2NjkzNy85MTQ5MzQ4LmpwZw==/347x500/jiCCrH.jpg',
      cr4: 'https://img.itch.zone/aW1nLzkxNDkyNzEuZ2lm/original/%2FDHBEI.gif',
      disponibilidad: true,
    },
    {
      id: 133,
      img: 'https://img.itch.zone/aW1nLzExNDIyOTA5LnBuZw==/315x250%23c/Fh7Bfi.png',
      nombre: 'Mold 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Stan vive en un lugar aislado con su esposa Mary. Su pasatiempo es la detección de metales. Tras encontrar un extraño amuleto, las cosas empiezan a ponerse realmente raras. ¿Es posible romper esta maldición? ¿Cuál es el origen de todo esto?...',
      cr1: 'https://i.ytimg.com/vi/OvhuqLP1Oyw/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTk0Mjk2NC8xMTQyMjg3MS5wbmc=/347x500/gCdVtH.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTk0Mjk2NC8xMTQyMjg3Ni5wbmc=/347x500/O5xsyh.png',
      cr4: 'https://img.itch.zone/aW1nLzExNDIyODIxLmdpZg==/original/fUUygZ.gif',
      disponibilidad: true,
    },
    {
      id: 134,
      img: 'https://img.itch.zone/aW1nLzg3NzcyNTgucG5n/315x250%23c/RiyyYX.png',
      nombre: 'Truth Loop',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Bryan se despierta tarde para recoger a su esposa del trabajo; ella sale muy tarde y no puede volver sola porque es demasiado peligroso... Así que él sale corriendo de la casa para encontrarla. Pero las cosas empiezan a ponerse realmente raras... La verdad saldrá a la luz.',
      cr1: 'https://img.itch.zone/aW1nLzg3NzU3OTQucG5n/original/9yr5vi.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTUwNTU1MS84Nzc2MDM3LmpwZw==/347x500/mhEIhf.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTUwNTU1MS84Nzc2MDQwLmpwZw==/347x500/ikF7jH.jpg',
      cr4: 'https://img.itch.zone/aW1nLzg3NzYxMTYuZ2lm/original/gTYEBy.gif',
      disponibilidad: true,
    },
    {
      id: 135,
      img: 'https://img.itch.zone/aW1nLzEyODYxODExLnBuZw==/315x250%23c/QLcUCk.png',
      nombre: 'Truth Loop 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Un soldado alemán despierta en un lugar frío y totalmente destruido... pero se da cuenta de que está atrapado allí y a cada momento descubre que ha hecho cosas terribles...',
      cr1: 'https://img.itch.zone/aW1nLzExNzY2NDY5LnBuZw==/original/7yl4XQ.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjAwMTQ2My8xMTc2NjY2NS5wbmc=/347x500/xKIkE3.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjAwMTQ2My8xMTc2NjY2OC5wbmc=/347x500/oZFTKS.png',
      cr4: 'https://img.itch.zone/aW1nLzExNzY2Nzc5LmdpZg==/original/XedXmN.gif',
      disponibilidad: true,
    },
    {
      id: 136,
      img: 'https://img.itch.zone/aW1nLzk1OTM0NDQucG5n/315x250%23c/UJnE3o.png',
      nombre: 'After Midnight',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Brad está solo en casa todas las noches; no tiene padre y su madre trabaja en un hospital en el turno de noche. Tras recibir algunos mensajes desconocidos en su teléfono móvil, las cosas empiezan a ponerse muy raras. Una noche tranquila y lluviosa se convierte en una pesadilla cuando un maníaco decide irrumpir en tu casa y jugar con tu mente.',
      cr1: 'https://img.itch.zone/aW1nLzg3NjA5MjcucG5n/original/GTy8rT.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTUwMjg0NC84NzYwOTMxLmpwZw==/347x500/CRcVy2.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTUwMjg0NC84NzYwOTM2LmpwZw==/347x500/q4C9wj.jpg',
      cr4: 'https://img.itch.zone/aW1hZ2UvMTUwMjg0NC84NzYwOTQxLmpwZw==/347x500/T%2Ba%2BTQ.jpg',
      disponibilidad: true,
    },
    {
      id: 137,
      img: 'https://img.itch.zone/aW1nLzEwNTQ3MjY0LnBuZw==/315x250%23c/M2Df0p.png',
      nombre: 'After Midnight 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Es la noche de Halloween y Mary ha sido contratada como niñera para cuidar de Drake, un niño de 7 años. Se suponía que sería una noche tranquila... pero un terrible asesino aparece para hacerle la vida imposible a Mary.',
      cr1: 'https://img.itch.zone/aW1nLzEwNTQ3Mjc5LnBuZw==/original/gEzMn3.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTc4NTA0Ni8xMDU0ODM2NS5qcGc=/347x500/ngocaf.jpg',
      cr3: 'https://img.itch.zone/aW1nLzEwNTQ4NDc3LmdpZg==/original/5lOi16.gif',
      cr4: 'https://img.itch.zone/aW1hZ2UvMTc4NTA0Ni8xMDU0ODM3Mi5qcGc=/347x500/aCj6S%2B.jpg',
      disponibilidad: true,
    },
    {
      id: 138,
      img: 'https://img.itch.zone/aW1nLzg4MzE2NzgucG5n/315x250%23c/5qxKMf.png',
      nombre: 'The House of Rats',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Ray hereda una antigua casa de su difunto abuelo... Entusiasmado, pronto se muda a la nueva casa y comienza a renovarla. Durante la reforma de la casa, Ray comienza a descubrir cosas terribles sobre el lugar y el pasado de su abuelo.',
      cr1: 'https://i.ytimg.com/vi/CZvKIylBmzk/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTUxNDcwOC84ODMyMDkxLmpwZw==/347x500/v44lyH.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTUxNDcwOC84ODMyMDg5LmpwZw==/347x500/2l%2FKn6.jpg',
      cr4: 'https://img.itch.zone/aW1nLzg4MzIxNDIuZ2lm/original/N80izw.gif',
      disponibilidad: true,
    },
    {
      id: 139,
      img: 'https://img.itch.zone/aW1nLzExMzI1Mzg3LnBuZw==/315x250%23c/AEZ3rK.png',
      nombre: 'REC',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Myers, un investigador policial, recibe una cinta VHS. Esta cinta contiene pruebas de un crimen, hallada en una vieja casa abandonada que perteneció a un asesino en serie conocido como "el maníaco de la guadaña".',
      cr1: 'https://img.itch.zone/aW1nLzExMzI0ODE0LnBuZw==/original/zhGZkH.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTkyNjIwMC8xMTMyNDc5NC5wbmc=/347x500/ZtZf1%2F.png',
      cr3: 'https://img.itch.zone/aW1nLzExMzI0ODQ3LmdpZg==/original/kkNOE%2B.gif',
      cr4: 'https://img.itch.zone/aW1nLzExMzI0ODU4LmdpZg==/original/jh7iFF.gif',
      disponibilidad: true,
    },
    {
      id: 140,
      img: 'https://img.itch.zone/aW1nLzExMjU4MTE1LnBuZw==/315x250%23c/QQv3zr.png',
      nombre: 'S.M.S',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Después de que la novia de Chance lo deja... él empieza a recibir mensajes extraños de su número. Lo que lo obliga a hacer cosas bastante raras.',
      cr1: 'https://i.ytimg.com/vi/_R0VWePbRGk/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTkxNTM5OS8xMTI2NDc3NS5wbmc=/347x500/OODaNA.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTkxNTM5OS8xMTI2NDc2OC5wbmc=/347x500/vy1yWl.png',
      cr4: 'https://img.itch.zone/aW1nLzExMjY0OTY1LmdpZg==/original/8nVyt%2B.gif',
      disponibilidad: true,
    },
    {
      id: 141,
      img: 'https://img.itch.zone/aW1nLzEwNDQ1MTg1LnBuZw==/315x250%23c/JV3GAx.png',
      nombre: 'Last Heir',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Dylan hereda una pequeña granja familiar de su abuelo. Tras mudarse allí, descubre que una gran maldición se cierne sobre el lugar.',
      cr1: 'https://i.ytimg.com/vi/52q3rc2WkNk/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTc3Njg4NC8xMDQ0ODk1OS5qcGc=/347x500/Fcuulf.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTc3Njg4NC8xMDQ0ODk2NC5qcGc=/347x500/3V%2Fik7.jpg',
      cr4: 'https://img.itch.zone/aW1nLzEwNDQ5MDQxLmdpZg==/original/M0IPxF.gif',
      disponibilidad: true,
    },
    {
      id: 142,
      img: 'https://img.itch.zone/aW1nLzkxNTA0MzUucG5n/315x250%23c/ikzKl0.png',
      nombre: 'Blood Burger',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Marco y su amigo Thales van a abrir una hamburguesería, pero no tienen ni idea de cocina. Así que deciden ir en busca de una fórmula secreta para hamburguesas en una fábrica abandonada de "ShitDonalds". Pero lo que no esperaban era que la mascota de la antigua fábrica siguiera allí.',
      cr1: 'https://img.itch.zone/aW1nLzg5MDIzNTkucG5n/original/Uxydtc.png',
      cr2: 'https://img.itch.zone/aW1nLzg5MDI1MTQuZ2lm/original/c%2F83Xf.gif',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTUyNjA3MS84OTAyNTc0LmpwZw==/347x500/o6KQB0.jpg',
      cr4: 'https://img.itch.zone/aW1nLzg5MDI1MTIuZ2lm/original/Xsg5F3.gif',
      disponibilidad: true,
    },
    {
      id: 143,
      img: 'https://img.itch.zone/aW1nLzEyNzc2MTQwLnBuZw==/315x250%23c/e37ovm.png',
      nombre: 'Cycle',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'John se despierta en su casa, sentado en una silla y con sangre por todo el suelo... Está confundido y no sabe muy bien cómo ha llegado allí.',
      cr1: 'https://img.itch.zone/aW1nLzEwMTQ5MjM2LnBuZw==/original/LeUPJZ.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTcyMzE2NC8xMDE1MDAwNS5qcGc=/347x500/%2FUbM%2Fp.jpg',
      cr3: 'https://img.itch.zone/aW1nLzEwMTUwMTczLmdpZg==/original/FckrRL.gif',
      cr4: 'https://img.itch.zone/aW1nLzEwMTUwMTc3LmdpZg==/original/TgoHAd.gif',
      disponibilidad: true,
    },
    {
      id: 144,
      img: 'https://img.itch.zone/aW1nLzEwMDM2MTgwLnBuZw==/315x250%23c/AMM3Xl.png',
      nombre: 'Chicken Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Un streamer con pocos recursos (Captain YG) sigue sin ganar dinero con sus vídeos y se ve obligado a trabajar en un pequeño restaurante de ramen. El restaurante es famoso por preparar el mejor pollo de la ciudad, y además, el más barato. Cuando necesitas matar un pollo para cocinarlo... Se activa una antigua profecía que te trae a un asesino despiadado para vengarse.',
      cr1: 'https://img.itch.zone/aW1nLzEwMDM2MDkzLnBuZw==/original/xLFlqm.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTcwMzU2NS8xMDAzNjMyNi5qcGc=/347x500/E3pt9x.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTcwMzU2NS8xMDAzNjMyNS5qcGc=/347x500/1pfwpr.jpg',
      cr4: 'https://img.itch.zone/aW1nLzEwMDM2NzEzLmdpZg==/original/C2U3%2BS.gif',
      disponibilidad: true,
    },
    {
      id: 145,
      img: 'https://img.itch.zone/aW1nLzk5OTc5MDkucG5n/315x250%23c/RQh2ln.png',
      nombre: 'Xenomoon',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Cuatro astronautas están en una misión a la Luna para recoger muestras de suelo. Pero las cosas empiezan a complicarse cuando Steffen descubre que no están solos...',
      cr1: 'https://img.itch.zone/aW1nLzk5OTc3NTYucG5n/original/oB0lOT.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTY5NzE0Mi85OTk3OTUwLmpwZw==/347x500/fnvwzj.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTY5NzE0Mi85OTk3OTUxLmpwZw==/347x500/3yPVt4.jpg',
      cr4: 'https://img.itch.zone/aW1nLzk5OTc4NDQuZ2lm/original/S0yEh6.gif',
      disponibilidad: true,
    },
    {
      id: 146,
      img: 'https://img.itch.zone/aW1nLzEzMDI2NTAzLnBuZw==/315x250%23c/78izg9.png',
      nombre: 'Gears',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Adam y sus amigos se reúnen para tomar una cerveza en un bar... Tras ser secuestrado por un asesino... tendrá que jugar un juego peligroso y mortal para salvar su vida y la de sus amigos.',
      cr1: 'https://i.ytimg.com/vi/QMcpC1UeHNk/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLB3xilfjlSd8oLu7L9ua7w12SXYGw',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTY4Mzg2OS85OTE3MzM5LmpwZw==/347x500/icX0OY.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTY4Mzg2OS85OTE3MzMzLmpwZw==/347x500/g97PtD.jpg',
      cr4: 'https://img.itch.zone/aW1nLzk5MTczMDMuZ2lm/original/Ap47Fy.gif',
      disponibilidad: true,
    },
    {
      id: 147,
      img: 'https://img.itch.zone/aW1nLzk3NTM0MjMucG5n/315x250%23c/eb2f0J.png',
      nombre: 'R.I.P.',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Kevin es un agente de policía que busca a un asesino muy peligroso. Tras recibir una llamada anónima, decide ir a ver qué tal es el lugar.',
      cr1: 'https://img.itch.zone/aW1nLzk3NjEzMjgucG5n/original/PPv%2FzR.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTY1NzQwNy85NzUzNDgxLmpwZw==/347x500/R0FLHA.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTY1NzQwNy85NzUzNDgwLmpwZw==/347x500/T0HhY%2F.jpg',
      cr4: 'https://img.itch.zone/aW1nLzk3NTMzODcuZ2lm/original/8qD2Kg.gif',
      disponibilidad: true,
    },
    {
      id: 148,
      img: 'https://img.itch.zone/aW1nLzEyMzU5MDk1LnBuZw==/315x250%23c/wzoNmi.png',
      nombre: 'Night of Carnage',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Adam es un adolescente de 13 años que vive con su madre en un barrio tranquilo... Cuando reciben la noticia de que hay un asesino suelto... Adam empieza a sospechar que su vecino podría ser el temido asesino.',
      cr1: 'https://i.ytimg.com/vi/COKeI7TjJAo/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTY0MDU4Ny85NjQ5MTk4LmpwZw==/347x500/e8AqYI.jpg',
      cr3: 'https://img.itch.zone/aW1nLzk2NDk0MDEuZ2lm/original/USzCUo.gif',
      cr4: 'https://img.itch.zone/aW1nLzk2NDkzODguZ2lm/original/7BYW9T.gif',
      disponibilidad: true,
    },
    {
      id: 149,
      img: 'https://img.itch.zone/aW1nLzEwMjQ0NjE4LnBuZw==/315x250%23c/0n6amv.png',
      nombre: 'Endless Night',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Dylan acepta un trabajo en una isla aislada cuidando el faro durante seis meses. El anterior farero ha desaparecido misteriosamente y, con el paso de los días, Dylan descubre que quizás no esté solo en la isla.',
      cr1: 'https://i.ytimg.com/vi/FgKGxk3b6Ek/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTU0NTMzNC85MDE2NTA5LmpwZw==/347x500/rDvLQY.jpg',
      cr3: 'https://img.itch.zone/aW1nLzkwMTYxMDQuZ2lm/original/LeZETz.gif',
      cr4: 'https://img.itch.zone/aW1nLzkwMTYxMDUuZ2lm/original/kzXqPP.gif',
      disponibilidad: true,
    },
    {
      id: 150,
      img: 'https://img.itch.zone/aW1nLzExODM2NzAzLnBuZw==/315x250%23c/cFvfh0.png',
      nombre: 'Endless Night 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Tras la misteriosa desaparición de algunos fareros, Matthews, un detective de policía, se dirige a la isla para investigar y averiguar qué está sucediendo. Acepta cuidar el faro durante seis meses mientras investiga la isla... Pero algo terrible está a punto de suceder...',
      cr1: 'https://i.ytimg.com/vi/wHZ4Qmf_p0I/sddefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjAxMjk4NC8xMTgzNjY1NC5qcGc=/347x500/w65eH9.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjAxMjk4NC8xMTgzNjY1My5qcGc=/347x500/rf25Ib.jpg',
      cr4: 'https://img.itch.zone/aW1nLzExODM2ODA1LmdpZg==/original/kCDd0R.gif',
      disponibilidad: true,
    },
    {
      id: 151,
      img: 'https://img.itch.zone/aW1nLzEwMTUwMzkyLnBuZw==/315x250%23c/cSqrKA.png',
      nombre: 'Dick Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Un maníaco sexual anda suelto... Le encanta comer culos... ¡y hará cualquier cosa por comerse el tuyo!',
      cr1: 'https://img.itch.zone/aW1nLzk1Njk4MDYucG5n/original/croa0F.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTYyNzg5NC85NTY5MjkwLmpwZw==/347x500/H3It9W.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTYyNzg5NC85NTY5MTI3LnBuZw==/347x500/Z2n%2FYu.png',
      cr4: 'https://img.itch.zone/aW1nLzk1NjkyNTAuZ2lm/original/J88hmS.gif',
      disponibilidad: true,
    },
    {
      id: 152,
      img: 'https://img.itch.zone/aW1nLzkzMDYxOTMucG5n/315x250%23c/YoRC%2Fd.png',
      nombre: 'We Are Not Alone',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Nick vive solo en una granja con su perro Jake. El lugar está aislado de la ciudad y es muy tranquilo, hasta que extraños objetos comienzan a aparecer en el cielo y seres de otro mundo comienzan a visitarte.',
      cr1: 'https://img.itch.zone/aW1nLzkzMDYxMDEucG5n/original/Paf1xO.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTU5MTc5Ny85MzA2NTU5LmpwZw==/347x500/rbq6vL.jpg',
      cr3: 'https://img.itch.zone/aW1nLzkzMDY3MjguZ2lm/original/jHWBXl.gif',
      cr4: 'https://img.itch.zone/aW1nLzkzMDY3MjMuZ2lm/original/8dXc3s.gif',
      disponibilidad: true,
    },
    {
      id: 153,
      img: 'https://img.itch.zone/aW1nLzkyNTk4NTUucG5n/315x250%23c/yJ0gSK.png',
      nombre: 'Thursday The 12th',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Mike y sus amigos Greg, Samantha y Madison se reúnen para ir de acampada. Las chicas los retan a entrar en la casa abandonada de un asesino en serie. Greg y Mike acceden sin pensarlo dos veces, ya que recibirán una buena recompensa. Pero el asesino sigue suelto... y odia a la gente que entra sin permiso en su casa.',
      cr1: 'https://img.itch.zone/aW1nLzkyNjA3NDkucG5n/original/D4JiWQ.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTU4NDE0NC85MjYwNjEwLmpwZw==/347x500/Gdrppn.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTU4NDE0NC85MjYwNjA4LmpwZw==/347x500/kSS4uL.jpg',
      cr4: 'https://img.itch.zone/aW1nLzkyNjA4MTIuZ2lm/original/ydBlrm.gif',
      disponibilidad: true,
    },
    {
      id: 154,
      img: 'https://img.itch.zone/aW1nLzk2ODkwNTEucG5n/315x250%23c/WAp4jI.png',
      nombre: 'Legend Hunters',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'El equipo de 7 miembros "Cazadores de Leyendas" investiga casos paranormales y busca espíritus malignos. Ponte en la piel de Tommy, uno de los miembros del equipo, e investiga la casa de un antiguo asesino en serie.',
      cr1: 'https://i.ytimg.com/vi/i779RDX5t1M/maxresdefault.jpg',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTU5NzEwNi85MzQyMzU3LmpwZw==/347x500/ZJ0Vh1.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTU5NzEwNi85MzQyMzUxLmpwZw==/347x500/GWIUOy.jpg',
      cr4: 'https://img.itch.zone/aW1nLzkzNDk4NDcuZ2lm/original/BIBWp5.gif',
      disponibilidad: true,
    },
    {
      id: 155,
      img: 'https://img.itch.zone/aW1nLzc5ODkxNDAucG5n/315x250%23c/PhUXFj.png',
      nombre: 'Midnight Tales Vol. 1',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Rachel trabaja de noche en una tienda de cintas VHS cuando decide ver una película que narra una serie de sucesos extraños y el resurgimiento de una secta conocida como "El Resplandor". De este modo, se logra una experiencia de inmersión total, conectando todo en uno',
      cr1: 'https://img.itch.zone/aW1nLzc5Nzg5MjMucG5n/original/T03G%2Bz.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTM3MDMxOC83OTg5MDgyLnBuZw==/347x500/pTPXKC.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTM3MDMxOC83OTg5MDgzLnBuZw==/347x500/sMH85V.png',
      cr4: 'https://img.itch.zone/aW1nLzc5Nzg5NjAucG5n/original/Af%2FqmQ.png',
      disponibilidad: true,
    },
    {
      id: 156,
      img: 'https://img.itch.zone/aW1nLzg0NDYxODcuZ2lm/315x250%23c/HC%2FH6v.gif',
      nombre: 'Midnight Tales Vol. 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'A Josh le apasionan los juegos de terror más extraños... Recibe una visita inusual en su casa: un hombre vestido de negro con una máscara. Ahora tendrá que realizar tareas bastante raras y sangrientas para poder jugar a nuevos juegos de terror. El modo historia reúne todos los juegos para enriquecer la trama y ofrecer una mayor inmersión a los jugadores.',
      cr1: 'https://img.itch.zone/aW1nLzg0NDUxODAucG5n/original/%2BHBxxd.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTQ0NjQ2MC84NDQ1Mzg4LmpwZw==/347x500/d%2FYTv3.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTQ0NjQ2MC84NDQ1NDIxLmpwZw==/347x500/CUqV%2F9.jpg',
      cr4: 'https://img.itch.zone/aW1nLzg0NDUyOTUucG5n/original/WUlwae.png',
      disponibilidad: true,
    },
    {
      id: 157,
      img: 'https://img.itch.zone/aW1nLzEwODQ4NDI0LnBuZw==/315x250%23c/LyaSMZ.png',
      nombre: 'Midnight Tales Vol. 3',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'En plena Navidad, un hombre le cuenta a su hija unas historias de terror... pero algo anda muy mal...',
      cr1: 'https://i0.wp.com/videojuerguistas.net/wp-content/uploads/2023/12/midnight-tales-02.jpg?resize=900%2C506&ssl=1',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTg0ODE5MC8xMDg0ODI0Mi5qcGc=/347x500/x3RJhq.jpg',
      cr3: 'https://img.itch.zone/aW1nLzEwODQ4MTg3LmdpZg==/original/q%2BrADt.gif',
      cr4: 'https://img.itch.zone/aW1nLzEwODQ4MTkyLmdpZg==/original/dgz1rb.gif',
      disponibilidad: true,
    },
    {
      id: 158,
      img: 'https://img.itch.zone/aW1nLzkxNTAyMzkucG5n/315x250%23c/k95kWB.png',
      nombre: 'Night Revenge',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Samantha sufre un intento de asesinato, pero logra golpear al asesino con una lámpara y llamar a la policía para que lo arresten. Veinte años después, recupera su libertad y hará lo que siempre soñó... ¡vengarse!',
      cr1: 'https://img.itch.zone/aW1nLzkxMDAxNjgucG5n/original/1KKYUH.png',
      cr2: 'https://img.itch.zone/aW1nLzkxMDA1NDQuZ2lm/original/krujf7.gif',
      cr3: 'https://img.itch.zone/aW1nLzkxMDA1NDguZ2lm/original/%2BPunDq.gif',
      cr4: 'https://img.itch.zone/aW1hZ2UvMTU1OTI2OS85MTAwMzk5LmpwZw==/347x500/4h5sgN.jpg',
      disponibilidad: true,
    },
    {
      id: 159,
      img: 'https://img.itch.zone/aW1nLzkwNjA4MzMucG5n/315x250%23c/5HWmmU.png',
      nombre: 'Red Valley',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Una ciudad vacía y destruida, un misterio aterrador, una oportunidad para descubrir la verdad. Samuel y Lisa viajaban en coche cuando sufrieron un accidente en la carretera. Lisa desaparece misteriosamente y Sam es llevado a un lugar desconocido. Ahora tendrás que guiar a Sam a través de la ciudad de "Red Valley", un lugar aterrador y morboso rodeado de misterios. A veces, el mal reside en nuestra propia mente.',
      cr1: 'https://img.itch.zone/aW1nLzg2NzgwNTYucG5n/original/3GYDoX.png',
      cr2: 'https://img.itch.zone/aW1nLzg2NzgxOTMuZ2lm/original/hI6fLz.gif',
      cr3: 'https://img.itch.zone/aW1nLzg2NzgxNzAuZ2lm/original/T0x%2BfK.gif',
      cr4: 'https://img.itch.zone/aW1nLzg2NzgxMzQuZ2lm/original/KVLzPX.gif',
      disponibilidad: true,
    },
    {
      id: 160,
      img: 'https://img.itch.zone/aW1nLzExNjk4NjM0LnBuZw==/315x250%23c/Ucldjt.png',
      nombre: 'Evil Is Back',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Scott y sus amigos van a pasar el fin de semana en una cabaña en el bosque, aislados de la ciudad. Al encontrar un libro muy antiguo y recitar accidentalmente algunas palabras... se abre el portal al mundo de los muertos, trayendo muerte y destrucción a todos los que se encuentran allí.',
      cr1: 'https://img.itch.zone/aW1nLzExNjk4NTQwLnBuZw==/original/C3LttN.png',
      cr2: 'https://img.itch.zone/aW1nLzExNjk4NTUxLmdpZg==/original/0g8uQ9.gif',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTk4OTgwOC8xMTY5ODU2OS5qcGc=/347x500/JK0Zfa.jpg',
      cr4: 'https://img.itch.zone/aW1nLzExNjk4NTQ3LmdpZg==/original/4%2FeGeO.gif',
      disponibilidad: true,
    },
    {
      id: 161,
      img: 'https://img.itch.zone/aW1nLzkxNTA3MDkucG5n/315x250%23c/VXjogr.png',
      nombre: 'The Clown’s Fun',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Un asesino extravagante... Un trabajo tedioso... Una noche demasiado tranquila para ser verdad. Steve trabaja de noche en un minimercado, aislado de la ciudad. Cuando te encuentras con otro psicópata... Un monstruo con máscara de payaso que secuestra gente y juega a la vida o a la muerte. Le gusta divertirse...',
      cr1: 'https://img.itch.zone/aW1nLzg1OTkwODkucG5n/original/DR%2FEXi.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTQ3NDM0OC84NzEwNjE3LmpwZw==/347x500/ie2G0R.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTQ3NDM0OC84NzEwNjI1LmpwZw==/347x500/hczxw%2F.jpg',
      cr4: 'https://img.itch.zone/aW1hZ2UvMTQ3NDM0OC84NzEwNjIwLmpwZw==/347x500/kq1inr.jpg',
      disponibilidad: true,
    },
    {
      id: 162,
      img: 'https://img.itch.zone/aW1nLzg5NjQ4NDQuZ2lm/315x250%23c/ksH7cS.gif',
      nombre: 'The Island Mystery',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'José trabaja como pescador en alta mar cuando se enfrenta a una tormenta y acaba hundiéndose solo en una isla desierta. Tras explorar la isla, empieza a notar que las cosas son diferentes de lo normal.',
      cr1: 'https://img.itch.zone/aW1nLzg5NjQxNjcucG5n/original/EVQiih.png',
      cr2: 'https://img.itch.zone/aW1nLzg5NjQyMTQuZ2lm/original/PLJA%2FH.gif',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTUzNjgwNi84OTY0MDY0LmpwZw==/347x500/koEKIc.jpg',
      cr4: 'https://img.itch.zone/aW1hZ2UvMTUzNjgwNi84OTY0MDcwLmpwZw==/347x500/Z8VTwj.jpg',
      disponibilidad: true,
    },
    {
      id: 163,
      img: 'https://img.itch.zone/aW1nLzk3MDMzMjYuanBn/315x250%23c/HH16dQ.jpg',
      nombre: 'Footage 1985',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'En febrero de 1986, se encontró una cinta en la antigua casa del asesino conocido como el "Carnicero del Bosque". Tras la desaparición de algunas personas en el lugar de los hechos, se inició una investigación. Mark Henry, el temido asesino, ya ha sido ejecutado en la silla eléctrica, por lo que no hay posibilidad de que sea el autor de más crímenes. Las imágenes que verás provienen de la cinta encontrada en el lugar y pueden resultar perturbadoras...',
      cr1: 'https://img.itch.zone/aW1nLzg5NDg1MjgucG5n/original/WRjpcA.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTUzNDI2Mi84OTQ4ODMwLmpwZw==/347x500/Ld4uxa.jpg',
      cr3: 'https://img.itch.zone/aW1hZ2UvMTUzNDI2Mi84OTQ4ODMyLmpwZw==/347x500/IKVKoG.jpg',
      cr4: 'https://img.itch.zone/aW1nLzg5NDkwMDMuZ2lm/original/dc877a.gif',
      disponibilidad: true,
    },
    {
      id: 164,
      img: 'https://img.itch.zone/aW1nLzEyMzQ2OTk1LnBuZw==/315x250%23c/qhPg31.png',
      nombre: 'The Dead are Not Dead',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Cinco años después de que el mundo fuera devastado por un virus zombie, Alfred busca a Jake, su hermano mayor. Se enfrenta a un escenario postapocalíptico y a muchos zombies sedientos de carne. Con su guitarra a cuestas, Alfred emprende un peligroso viaje del que quizás no haya vuelta atrás. Este juego simula la estética y la sensación de los juegos de terror de supervivencia de la era de PS1. Utiliza controles tipo tanque y una cámara en tercera persona. Si tienes problemas con los juegos de controles tipo tanque, este juego no te gustará. No tiene guardado automático; debes guardar la partida con tinta en una máquina de escribir, que puedes encontrar durante el juego. Inspirado en las películas de terror de culto de los 80, trae un estilo de terror de las películas de bajo presupuesto de la era VHS.',
      cr1: 'https://img.itch.zone/aW1nLzEyMzQ2OTEzLnBuZw==/original/sDQJV3.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjA5ODI5MC8xMjM0Njk4NC5wbmc=/347x500/lKp1zT.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjA5ODI5MC8xMjM0Njk4MC5wbmc=/347x500/3yzgCC.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjA5ODI5MC8xMjM0Njk4MS5wbmc=/347x500/RUV0Qr.png',
      disponibilidad: true,
    },
    {
      id: 165,
      img: 'https://img.itch.zone/aW1nLzkxNTkyNTMucG5n/315x250%23c/9dAnZL.png',
      nombre: 'Panic on Ice',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Jessy está de viaje de negocios, pero un accidente aéreo lo coloca en una situación desesperada. Aislado en el inhóspito entorno de Alaska, tendrá que enfrentarse al frío glacial y luchar por sobrevivir. Además de la horrible situación en la que se encuentra, todavía tendrá que lidiar con maníacos caníbales... "¡Muere de frío... o a punta de hacha!"',
      cr1: 'https://img.itch.zone/aW1nLzg1MTc3MzgucG5n/original/lSckuu.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTQ1ODYzNS84NTIxNDExLmpwZw==/347x500/zUJkws.jpg',
      cr3: 'https://img.itch.zone/aW1nLzg1MjI1MjEuZ2lm/original/3uP2CI.gif',
      cr4: 'https://img.itch.zone/aW1nLzg1MjI1MjYuZ2lm/original/wou2z7.gif',
      disponibilidad: true,
    }
  ];
 constructor(private carritoService: CarritoCompras, private listaDeseadosService: ListaDeseados) { }
 
   agregarAlCarrito(producto: Producto): void {
     this.carritoService.agregar(producto);
     alert(`${producto.nombre} agregado al carrito`);
   }
 
   agregarAListaDeseados(producto: Producto): void {
   this.listaDeseadosService.agregar(producto);
   alert(`${producto.nombre} agregado a la lista de deseados`);
 }
}
