import { Component } from '@angular/core';
import { Producto } from '../../../models/producto';
import { CarritoCompras } from '../../../servicios/carrito';
@Component({
  selector: 'app-six-one-six-games',
  imports: [],
  templateUrl: './six-one-six-games.html',
  styleUrl: './six-one-six-games.css',
})
export class SixOneSixGames {
  six: Producto[] = [
    {
      id: 1,
      img: '/assets/killer.jpg',
      nombre: 'I am a Serial Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 101,
      desc: 'Martin decidió unirse a una secta llamada "Los Iluminados", que busca dar vida a un ser misterioso para eliminar todo el mal del mundo. ¿Hasta dónde estás dispuesto a llegar para lograr tus metas?',
      cr1: 'https://img.itch.zone/aW1nLzEyNzcyODkyLnBuZw==/original/z2yhXR.png',
      cr2: 'https://img.itch.zone/aW1hZ2UvMjE1NDAxNS8xMjc2Mzk1OC5wbmc=/347x500/%2BqoXM7.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMjE1NDAxNS8xMjc2Mzk1My5wbmc=/347x500/saRoCe.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMjE1NDAxNS8xMjc2Mzk1Mi5wbmc=/347x500/%2BoZjsk.png',
      disponibilidad: true,
    },
    {
      id: 102,
      img: '/assets/pop.png',
      nombre: 'Poop Killer 4',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1,
      desc: 'Tras la muerte del "Asesino de las Cacas", la gente está más tranquila y puede volver a defecar en paz. Pero un fanático decide imitar a este terrible asesino... Billy es dueño de una "Sex Shop", una tienda dirigida a hombres homosexuales. Después de que un cliente defeca y obstruye el baño, la situación se vuelve tensa.',
      cr1: 'https://img.itch.zone/aW1nLzEyMjcyOTgzLnBuZw==/original/tR0ZKb.png',
      cr2: 'https://img.itch.zone/aW1nLzk2OTQyNTUuZ2lm/original/ssSFnh.gif',
      cr3: 'https://img.itch.zone/aW1nLzk2OTQyOTUuZ2lm/original/R5y096.gif',
      cr4: 'https://img.itch.zone/aW1nLzk2OTQyODUuZ2lm/original/jydj9x.gif',
      disponibilidad: true,
    },
    {
      id: 103,
      img: '/assets/blood.jpg',
      nombre: 'Blood Camp',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'Blood Camp es un juego de terror slasher de estilo retro, desarrollado por 616 Games y lanzado en 2022, que rinde homenaje a las películas de terror de bajo presupuesto de los años 80 y 90',
      cr1: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/header.jpg?t=1645726691',
      cr2: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/ss_4758dc5c34e9b0b88010c964f3ac9c697cda8cce.1920x1080.jpg?t=1645726691',
      cr3: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/ss_a2d7bd44771625b3c4c944ad1d5286fc907e38ce.1920x1080.jpg?t=1645726691',
      cr4: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1903780/ss_e2445b0157bf84a5b076777e56b0bd014dd9639b.1920x1080.jpg?t=1645726691',
      disponibilidad: true,
    },
    {
      id: 104,
      img: '/assets/indicted.jpg',
      nombre: 'Indicted',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 1.99,
      desc: 'INDICTED es un juego de terror psicológico en primera persona que explora los miedos de Arthur, un investigador policial con un pasado oscuro. Con gráficos y escenarios inmersivos, y un toque de terror de los años 80 y 90, ofrece una experiencia única de terror y supervivencia.',
      cr1: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/header.jpg?t=1635550118',
      cr2: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/ss_c5e348a8ed06d00417676aca7d8f0234c6449691.1920x1080.jpg?t=1635550118',
      cr3: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/ss_5fa528c412b2e791539b7aaa7bd5e74b80956bf9.1920x1080.jpg?t=1635550118',
      cr4: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1463420/ss_0121a4fbb305d1ab5d6efb9344ba96e87de53f6e.1920x1080.jpg?t=1635550118',
      disponibilidad: true,
    },
    {
      id: 105,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big_2x/cob2j2.jpg',
      nombre: 'Tales Beyond The Bomb: White Silence',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 106,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9jt5.webp',
      nombre: 'Poop Killer: Flush or Die',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 107,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big_2x/cob2j1.jpg',
      nombre: 'Tales Beyond The Bomb: The Last Vigil',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 108,
      img: 'Tales Beyond The Bomb: Pineville Night Stalker',
      nombre: 'Tales Beyond The Bomb: Pineville Night Stalker',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 109,
      img: '',
      nombre: '1873',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 110,
      img: '',
      nombre: 'Gears 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 111,
      img: '',
      nombre: 'Fart Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 112,
      img: '',
      nombre: 'Halloween Revenge',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 113,
      img: '',
      nombre: 'Dad',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 114,
      img: '',
      nombre: 'We Are Not Alone: Contact',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 115,
      img: 'https://external-preview.redd.it/trash-night-gameplay-616-games-v0-77HLPzUNpgh6eVbUWJ8uOqdm45ffr-LdNFltAVNO1b4.jpg?format=pjpg&auto=webp&s=e34308f9b3f985c2b07dd06ec025bd7335abc1e6',
      nombre: 'Trash Night',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 116,
      img: '',
      nombre: 'Meat',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 117,
      img: '',
      nombre: 'Community',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 118,
      img: '',
      nombre: 'The Light Went Out',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 119,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7kie.webp',
      nombre: 'Poop Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 120,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co857k.webp',
      nombre: 'Poop Killer 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 121,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co857k.webp',
      nombre: 'Poop Killer 3',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 122,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5xo7.webp',
      nombre: 'Poop Killer 5',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 123,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5zm5.webp',
      nombre: 'Poop Killer 6',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 124,
      img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6l0d.webp',
      nombre: 'Poop Killer 7',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 125,
      img: 'https://pbs.twimg.com/media/GBfRmNMXIAAeuQz.png',
      nombre: 'Poop Killer 8',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 126,
      img: '',
      nombre: 'Hello, I Came to Kill You',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 127,
      img: '',
      nombre: 'Deer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 128,
      img: '',
      nombre: 'Hill Maniac',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 129,
      img: '',
      nombre: 'Bloody Woman',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 130,
      img: '',
      nombre: 'Poop Killer Origins',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 131,
      img: '',
      nombre: 'The Elevator',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 132,
      img: '',
      nombre: 'Mold',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 133,
      img: '',
      nombre: 'Mold 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 134,
      img: '',
      nombre: 'Truth Loop',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 135,
      img: '',
      nombre: 'Truth Loop 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 136,
      img: '',
      nombre: 'After Midnight',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 137,
      img: '',
      nombre: 'After Midnight 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 138,
      img: '',
      nombre: 'The House of Rats',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 139,
      img: '',
      nombre: 'REC',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 140,
      img: '',
      nombre: 'S.M.S.',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 141,
      img: '',
      nombre: 'Last Heir',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 142,
      img: '',
      nombre: 'Blood Burger',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 143,
      img: '',
      nombre: 'Cycle',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 144,
      img: '',
      nombre: 'Chicken Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 145,
      img: '',
      nombre: 'Xenomoon',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 146,
      img: '',
      nombre: 'Gears',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 147,
      img: '',
      nombre: 'R.I.P.',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 148,
      img: '',
      nombre: 'Night of Carnage',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 149,
      img: '',
      nombre: 'Endless Night',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 150,
      img: '',
      nombre: 'Endless Night 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 151,
      img: '',
      nombre: 'Dick Killer',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 152,
      img: '',
      nombre: 'We Are Not Alone',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 153,
      img: '',
      nombre: 'Thursday The 12th',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 154,
      img: '',
      nombre: 'Legend Hunters',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 155,
      img: '',
      nombre: 'Midnight Tales Vol. 1',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 156,
      img: '',
      nombre: 'Midnight Tales Vol. 2',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 157,
      img: '',
      nombre: 'Midnight Tales Vol. 3',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 158,
      img: '',
      nombre: 'Night Revenge',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 159,
      img: '',
      nombre: 'Red Valley',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 160,
      img: '',
      nombre: 'Evil Is Back',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 161,
      img: '',
      nombre: 'The Clown’s Fun',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 162,
      img: '',
      nombre: 'The Island Mystery',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 163,
      img: '',
      nombre: 'Footage 1985',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 164,
      img: '',
      nombre: 'They Are Not Dead',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 165,
      img: '',
      nombre: 'Panic on Ice',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 166,
      img: '',
      nombre: 'Stab',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 167,
      img: '',
      nombre: 'Black Butterfly',
      desarrolladora: '616 Games',
      link: '/616-games',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
  ];
 constructor(private carritoService: CarritoCompras) { }

  agregarAlCarrito(producto: Producto): void {
    this.carritoService.agregar(producto);
    alert(`${producto.nombre} agregado al carrito`);
  }
}
