import { Component } from '@angular/core';
import { Producto } from '../../models/producto';
@Component({
  selector: 'app-productos',
  imports: [],
  templateUrl: './productos.html',
  styleUrl: './productos.css',
})
export class Productos {
  productos: Producto[] = [
    {
       id: 1,
      img: 'https://store-images.s-microsoft.com/image/apps.57418.14163413953167753.5fb76bc9-9bdf-4576-9079-0e674a1d536c.d5b61dc7-c7b4-4e39-8231-f6154f78d590',
      nombre: 'Murder House',
      desarrolladora: 'Puppet Combo',
      precio: 11.99,
      desc: 'Un equipo de noticias local irrumpe en una casa abandonada para investigar una escabrosa historia de fantasmas... ¡hasta que un MANÍACO los persigue!',
      cr1: 'https://www.metacritic.com/a/img/resize/03d27b82e7ca8375e7fe53e155440e700c6ebe92/catalog/provider/6/12/6-1-822042-52.jpg?auto=webp&fit=contain&height=480',
      cr2: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1064460/ss_3f2f7ba81b9819709ffc5095d1157716e4319186.1920x1080.jpg?t=1669836425',
      cr3: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1064460/ss_39911e9a7655071cd79d93385db341bdc42aa2ad.1920x1080.jpg?t=1669836425',
      cr4: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1064460/ss_1a7a15f38e2698ac425db9f7103ab626afa8ffc6.1920x1080.jpg?t=1669836425',
      disponibilidad: true,
    },
      {
      id: 2,
      img: 'https://store-images.s-microsoft.com/image/apps.23865.13794259264775165.981f5991-3592-472c-af32-598bd0cf8390.57f0b1a1-61a8-4d04-9eb2-db1292bed1d0',
      nombre: 'nun Massacre',
      desarrolladora: 'Puppet Combo',
      precio: 4.95,
      desc: 'Una carta ha llegado a tu casa en circunstancias misteriosas... tu hija se ha enfermado en el internado. Cuando vas a buscarla, se desata una tormenta y el camino queda bloqueado. Sigues caminando por el bosque y pronto se desata el caos...',
      cr1: 'https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/store/software/switch/70010000048936/6c2cfc7a18785e0cc8402ce37133d9399534e8b75532cf5e45540cf12660f2bd',
      cr2: 'https://img.itch.zone/aW1nLzE1MjYzNDQuZ2lm/original/Tq5EuC.gif',
      cr3: 'https://img.itch.zone/aW1hZ2UvMzEwNTE1LzE1MjYzNTkuZ2lm/original/WDXLyK.gif',
      cr4: 'https://img.itch.zone/aW1hZ2UvMzEwNTE1LzE1MjYzMzcuZ2lm/original/OtKY3U.gif',
      disponibilidad: true,
    },
    {
      id: 3,
      img: 'https://image.api.playstation.com/vulcan/ap/rnd/202304/2618/42e39588e95f85e70c76a50a6830d2476e0f481136877cc2.png',
      nombre: 'Stay Out of the House',
      desarrolladora: 'Puppet Combo',
      precio: 14.99,
      desc: 'HORROR EN SIGILO que te tendrá al borde de tu asiento mientras intentas escapar de la casa de un ASESINO EN SERIE CANIBAL.',
      cr1: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/896520/capsule_616x353.jpg?t=1689365167',
      cr2: 'https://img.itch.zone/aW1hZ2UvMzM3MzMyOC8yMDE0MDI3Mi5wbmc=/347x500/TXgHtP.png',
      cr3: 'https://img.itch.zone/aW1hZ2UvMzM3MzMyOC8yMDE0MDI3MS5wbmc=/347x500/ETt1g5.png',
      cr4: 'https://img.itch.zone/aW1hZ2UvMzM3MzMyOC8yMDE0MDI5NS5wbmc=/347x500/GYQZ3K.png',
      disponibilidad: true,
    },
    {
      id: 4,
      img: '/assets/night.jpg',
      nombre: 'Night Shift',
      desarrolladora: 'Puppet Combo',
      precio: 14.99,
      desc: ' Lo que comienza como una rutina de reponer estantes y barrer el piso rápidamente se convierte en un descenso vertiginoso hacia la paranoia, el pavor y la locura empapada de sangre a medida que el asesino se acerca',
      cr1: 'https://i.ytimg.com/vi/TAUnOcIw2Lc/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCrUul3MEOharjjSOyLIOKBxGqcEA',
      cr2: 'https://img.itch.zone/aW1hZ2UvMTA1OTUyNy82MDY0MzI4LmpwZw==/original/ggZ9Po.jpg',
      cr3: 'https://i.ytimg.com/vi/3gdK7GQAz24/maxresdefault.jpg',
      cr4: 'https://i.ytimg.com/vi/i8kP15Rl_VA/maxresdefault.jpg',
      disponibilidad: true,
    },
    // Chilla's Art
    {
      id: 5,
      img: '/assets/store.jpg',
      nombre: 'The Convenience Store',
      desarrolladora: 'Chilla\'s Art',
      precio: 2.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 6,
      img: '/assets/shift.jpg',
      nombre: 'The Closing Shift',
      desarrolladora: 'Chilla\'s Art',
      precio: 5.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 7,
      img: '/assets/bath.png',
      nombre: 'The Bathhouse',
      desarrolladora: 'Chilla\'s Art',
      precio: 4.49,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 8,
      img: '/assets/delivery.jpg',
      nombre: 'Night Delivery',
      desarrolladora: 'Chilla\'s Art',
      precio: 2.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    // Torture Star Video
    {
      id: 9,
      img: 'https://store-images.s-microsoft.com/image/apps.673.14599123363525861.62176224-5ddf-418c-a312-67f7bacf9abf.c39649ab-d502-4caa-a2da-c9557785e22a',
      nombre: 'Bloodwash',
      desarrolladora: 'Torture Star Video',
      precio: 7.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 10,
      img: '/assets/sniper.jpg',
      nombre: 'Sniper Killer',
      desarrolladora: 'Sniper Killer',
      precio: 6.59,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 11,
      img: '/assets/salazar.jpg',
      nombre: 'The Horror of Salazar House',
      desarrolladora: 'Torture Star Video',
      precio: 3.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 12,
      img: '/assets/rewind.jpg',
      nombre: 'Rewind or Die',
      desarrolladora: 'Torture Star Video',
      precio: 11.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    // 616 Games
    {
      id: 13,
      img: '/assets/killer.jpg',
      nombre: 'I am a Serial Killer',
      desarrolladora: '616 Games',
      precio: 0.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 14,
      img: '/assets/pop.png',
      nombre: 'Poop Killer 4',
      desarrolladora: '616 Games',
      precio: 0.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 15,
      img: '/assets/blood.jpg',
      nombre: 'Blood Camp',
      desarrolladora: '616 Games',
      precio: 1.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 16,
      img: '/assets/indicted.jpg',
      nombre: 'Indicted',
      desarrolladora: '616 Games',
      precio: 1.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    // Emika Games
    {
      id: 17,
      img: '/assets/summer.jpg',
      nombre: 'Summer of \'58',
      desarrolladora: 'Emika Games',
      precio: 3.51,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 18,
      img: '/assets/loked.jpg',
      nombre: 'Locked Up',
      desarrolladora: 'Emika Games',
      precio: 3.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 19,
      img: '/assets/callus.jpg',
      nombre: 'Callus',
      desarrolladora: 'Emika Games',
      precio: 2.41,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 20,
      img: '/assets/Fathers_Day.jpg',
      nombre: 'Father\'s Day',
      desarrolladora: 'Emika Games',
      precio: 2.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    // Yames
    {
      id: 21,
      img: '/assets/discover.jpg',
      nombre: 'Discover My Body',
      desarrolladora: 'Yames',
      precio: 0.00,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 22,
      img: '/assets/water.jpg',
      nombre: 'Water Womb World',
      desarrolladora: 'Yames',
      precio: 0.00,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 23,
      img: '/assets/growing.png',
      nombre: 'Growing My Grandpa!',
      desarrolladora: 'Yames',
      precio: 4.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 24,
      img: '/assets/plastic.jpg',
      nombre: 'Plastic Spouse Interrogation',
      desarrolladora: 'Yames',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    // Varios
    {
      id: 25,
      img: '/assets/imscared.png',
      nombre: 'IMSCARED',
      desarrolladora: 'Ivan Zanotti\'s MyMadnessWorks',
      precio: 2.49,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 26,
      img: '/assets/cry.jpg',
      nombre: 'Cry of Fear',
      desarrolladora: 'Team Psykskallar',
      precio: 0,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 27,
      img: '/assets/iron.jpg',
      nombre: 'Iron Lung',
      desarrolladora: 'David Szymanski',
      precio: 4.49,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    },
    {
      id: 28,
      img: '/assets/scissors.jpg',
      nombre: 'The Night of the Scissorsk',
      desarrolladora: 'Tomás Esconjaureguyi',
      precio: 1.99,
      desc: '',
      cr1: '',
      cr2: '',
      cr3: '',
      cr4: '',
      disponibilidad: true,
    }
  ];
}
